"""Plain-English glossary for Be The Puck.

Each entry:
  slug     anchor id on /learn/glossary/
  term     display name
  topic    section on the glossary page
  aliases  phrases that get linked in page text (first use per page).
           All-lower-case aliases match any case; an alias containing a
           capital letter (EMA, ETF, TFSA, Sharpe...) matches exactly.
  tip      one or two short sentences shown on hover
  body     the full entry (may contain simple HTML)
  lesson   optional "lesson-slug#anchor": links go to the lesson instead of
           the glossary, and the glossary entry points to it

Keep definitions short, concrete and free of other jargon where possible.
"""

TOPICS = [
    ("prices", "Prices and charts"),
    ("averages", "Moving averages and trends"),
    ("rules", "Rules and signals"),
    ("results", "Reading the results"),
    ("indicators", "Indicators, oscillators and stops"),
    ("patterns", "Breakouts, momentum and the calendar"),
    ("business", "The business behind the price"),
    ("macro", "Markets and the economy"),
    ("money", "Using it with real money"),
    ("desk", "The live desk"),
]

GLOSSARY = [
    # ------------------------------------------------------------ prices
    dict(slug="ticker", term="Ticker", topic="prices", aliases=["ticker", "tickers", "ticker symbol"],
         tip="The short code a stock trades under, like NVDA for Nvidia or RY.TO for Royal Bank on the Toronto exchange.",
         body="The short code a stock or fund trades under. NVDA is Nvidia. A suffix tells you the exchange: <b>.TO</b> is the Toronto Stock Exchange, <b>.V</b> is the TSX Venture Exchange, and <b>-USD</b> marks a cryptocurrency priced in US dollars."),
    dict(slug="closing-price", term="Closing price (the close)", topic="prices",
         aliases=["closing price", "closing prices", "daily close", "daily closes", "weekly close", "weekly closes", "month-end close", "month-end closes", "month-end price", "finished close", "finished closes"],
         tip="The last price a stock trades at when the market shuts for the day (4 pm New York time).",
         body="The last price of the trading day, at 4 pm New York time for US stocks. Every rule on Be The Puck looks only at closes, never at the price in the middle of the day, because intraday prices swing around and would trigger false signals. A <b>weekly close</b> is Friday's close; a <b>month-end close</b> is the close on the last trading day of the month.",
         lesson="reading-a-page#close"),
    dict(slug="adjusted-price", term="Adjusted price", topic="prices", aliases=["adjusted for splits and dividends", "adjusted price", "adjusted prices"],
         tip="A price history rewritten so stock splits and dividends don't show up as fake jumps or drops.",
         body="When a company splits its shares 2-for-1 the price halves overnight, and when it pays a dividend the price drops by that amount. Adjusted prices rewrite the history so those events don't look like real gains or losses. Be The Puck uses adjusted prices, so returns include dividends."),
    dict(slug="log-scale", term="Log scale", topic="prices", aliases=["log scale", "logarithmic scale"],
         tip="A chart scale where equal distances mean equal percentage changes, so a double from $10 to $20 looks the same as from $100 to $200.",
         body="On a normal chart, a move from $100 to $200 looks ten times bigger than a move from $10 to $20, even though both are a 100% gain. On a log scale, equal distances mean equal percentage changes. Be The Puck's growth charts use log scale so early years aren't squashed flat."),
    dict(slug="etf", term="ETF (exchange-traded fund)", topic="prices", aliases=["ETF", "ETFs", "exchange-traded fund", "exchange-traded funds"],
         tip="A fund that trades like a single stock but holds a basket of investments, such as all 500 stocks in the S&P 500.",
         body="A fund you buy and sell like a stock, but which holds a basket of investments. SPY holds the 500 stocks in the S&P 500; GLD holds gold; TLT holds long-term US government bonds. ETFs are the usual way to own a whole market in one trade."),
    dict(slug="index", term="Index", topic="prices", aliases=["index fund", "index funds", "market index", "stock index"],
         tip="A list of stocks used to measure a market, like the S&P 500 (500 big US companies) or the TSX 60.",
         body="A list of stocks used to track a market, such as the S&P 500 (500 large US companies), the Nasdaq-100, or Canada's S&P/TSX 60. You can't buy an index directly, but index funds and ETFs copy them."),
    dict(slug="market-cap", term="Market cap", topic="prices", aliases=["market cap", "market capitalization", "market value"],
         tip="What the whole company is worth on the stock market: share price times number of shares.",
         body="Share price multiplied by the number of shares: what the stock market says the whole company is worth. Apple is worth trillions of dollars; some micro caps on Be The Puck are worth under $10 million."),
    dict(slug="micro-cap", term="Micro cap", topic="prices", aliases=["micro cap", "micro caps", "micro-cap", "micro-caps", "small cap", "small caps", "small-cap", "small-caps"],
         tip="A very small public company, roughly under $300 million in value. Prices swing wildly and trading costs are high.",
         body="Small public companies, usually under about $300 million in market cap (small caps run up to a few billion). Their prices swing much more than big companies, few people trade them, and the gap between buying and selling prices is wide, so trading them costs more. Be The Puck's backtests assume 0.30% per switch for micro caps instead of 0.05% for that reason.",
         ),
    dict(slug="52-week-range", term="52-week high and low", topic="prices", aliases=["52-week high", "52-week low", "52-week range", "52-week highs", "52-week lows"],
         tip="The highest and lowest closing prices over the past year.",
         body="The highest and lowest prices over the last year. Mark Minervini's Trend Template wants a stock at least 30% above its 52-week low and within 25% of its 52-week high: well off the bottom and near the top."),
    dict(slug="currency-hedged", term="Currency-hedged", topic="prices", aliases=["currency-hedged", "currency hedged", "hedged ETF"],
         tip="A fund that removes the effect of exchange-rate moves, so you get the stock's move without the currency's.",
         body="A foreign stock bought in another currency moves with both the company and the exchange rate. A currency-hedged fund (like STHH, which holds STMicroelectronics) strips out the exchange-rate part so you only get the company's move."),

    # ------------------------------------------------------------ averages
    dict(slug="moving-average", term="Moving average", topic="averages", aliases=["moving average", "moving averages", "moving-average"],
         tip="The average closing price over the last set number of days, recalculated every day. It smooths out the noise to show the trend.",
         body="The average of the last <i>n</i> closing prices, recalculated each day so it 'moves' along with the price. A 50-day moving average is the average of the last 50 closes. It smooths out day-to-day noise so you can see which way the price is really heading. Every rule on Be The Puck is built on moving averages.",
         lesson="moving-averages#what"),
    dict(slug="sma", term="SMA (simple moving average)", topic="averages", aliases=["SMA", "SMAs", "simple moving average", "simple moving averages", "simple average"],
         tip="A moving average where every day counts equally: add up the last n closes and divide by n.",
         body="Add up the last <i>n</i> closes and divide by <i>n</i>. Every day counts equally, so a big move 49 days ago matters as much as yesterday's. That makes an SMA steady but slow to react.",
         lesson="moving-averages#sma-ema"),
    dict(slug="ema", term="EMA (exponential moving average)", topic="averages", aliases=["EMA", "EMAs", "exponential moving average", "exponential moving averages"],
         tip="A moving average that gives recent days more weight, so it reacts faster than a simple average.",
         body="A moving average that weights recent prices more heavily, so it turns faster than a simple moving average of the same length. A 21-day EMA reacts to a sharp drop within days; a 21-day SMA takes longer. Faster means earlier signals but also more false ones.",
         lesson="moving-averages#sma-ema"),
    dict(slug="band", term="Band (or cloud)", topic="averages", aliases=["two-EMA band", "EMA band", "EMA bands", "the band", "EMA cloud", "EMA clouds", "the cloud"],
         tip="The space between two moving averages, shaded on a chart. Price above it reads as strong, below it as weak, inside it as undecided.",
         body="The shaded space between two moving averages, such as a 12-day and 21-day EMA. Price above the whole band is read as an uptrend, below it as a downtrend, and inside it as undecided. Band rules on Be The Puck change their call only when price closes fully above or below the band, and hold their last call while price is inside it. That cuts down on false signals.",
         lesson="moving-averages#bands"),
    dict(slug="crossover", term="Crossover", topic="averages", aliases=["crossover", "crossovers", "crosses above", "crosses below"],
         tip="When a faster moving average moves above or below a slower one, often used as a buy or sell signal.",
         body="The moment a faster moving average moves above (or below) a slower one, or price crosses an average. Crossovers are the most common trigger in trend-following rules.",
         lesson="moving-averages#crossovers"),
    dict(slug="golden-cross", term="Golden cross and death cross", topic="averages", aliases=["golden cross", "death cross", "golden crosses", "death crosses"],
         tip="Golden cross: the 50-day average moves above the 200-day. Death cross: it moves below. Widely watched, but slow.",
         body="A golden cross is when the 50-day moving average rises above the 200-day; a death cross is the reverse. They're popular in financial media because they're simple, but by the time one happens much of the move has already occurred."),
    dict(slug="trend", term="Uptrend and downtrend", topic="averages", aliases=["uptrend", "uptrends", "downtrend", "downtrends", "confirmed uptrend"],
         tip="An uptrend is a run of higher highs and higher lows, usually with price above a rising moving average. A downtrend is the reverse.",
         body="An uptrend is a price that keeps making higher highs and higher lows, usually sitting above a rising moving average. A downtrend is the opposite. Trend-following rules try to own stocks in uptrends and step aside in downtrends."),
    dict(slug="support-resistance", term="Support and resistance", topic="averages", aliases=["support and resistance", "support/resistance"],
         tip="Support is a price level where falls tend to stop; resistance is a level where rises tend to stall.",
         body="Support is a price level (or a moving average) where declines have tended to stop and bounce. Resistance is a level where rallies have tended to stall. Traders watch both because many other traders are watching them too."),
    dict(slug="trend-following", term="Trend following", topic="averages", aliases=["trend following", "trend-following", "trend follower", "trend followers", "trend rules", "trend rule"],
         tip="Owning things while they're rising and getting out once they start falling, rather than trying to predict turns.",
         body="A strategy of owning an asset while its price trend is up and stepping aside when it turns down, instead of trying to predict tops and bottoms. It accepts being late on purpose: it gives up the start and end of every move in return for avoiding most of the long declines.",
         lesson="trend-following#idea"),
    dict(slug="momentum", term="Momentum", topic="averages", aliases=["momentum", "time-series momentum", "price momentum"],
         tip="The tendency of assets that have been rising to keep rising for a while, and falling ones to keep falling.",
         body="The tendency for prices that have been rising to keep rising for a while, and falling ones to keep falling. <b>Time-series momentum</b> compares an asset with its own past, for example 'is it higher than 12 months ago?', as in the Moskowitz, Ooi and Pedersen rule.",
         lesson="momentum#time-series"),
    dict(slug="bull-bear-market", term="Bull market and bear market", topic="averages", aliases=["bull market", "bull markets", "bear market", "bear markets"],
         tip="A bull market is a long stretch of rising prices; a bear market is a fall of 20% or more from the peak.",
         body="A bull market is a long period of rising prices. A bear market is usually defined as a fall of 20% or more from the last peak. Trend rules earn most of their keep in bear markets, by being out of the market for much of the fall."),
    dict(slug="stage-analysis", term="Stage 2 (Stage Analysis)", topic="averages", aliases=["Stage 2", "Stage Analysis", "stage analysis"],
         tip="Stan Weinstein's idea that stocks cycle through four stages; Stage 2 is the advancing stage, with price above a rising 30-week average.",
         body="Stan Weinstein's model of a stock's life: Stage 1 basing (flat), Stage 2 advancing (price above a rising 30-week moving average), Stage 3 topping, and Stage 4 declining. The rule is to own stocks only in Stage 2."),

    # ------------------------------------------------------------ rules
    dict(slug="trading-rule", term="Trading rule (strategy)", topic="rules", aliases=["trading rule", "trading rules", "timing rule", "timing rules", "published rule", "published rules"],
         tip="A fixed set of instructions that says when to own something and when not to, written down so anyone can test it.",
         body="A written-down set of instructions for when to own something and when not to, such as 'own it while the month-end price is above its 10-month average'. Because it's fixed, it can be tested on past prices and checked by anyone. Be The Puck tests seven of them."),
    dict(slug="signal", term="Signal", topic="rules", aliases=["signal", "signals", "buy signal", "sell signal"],
         tip="The output of a rule at a point in time: in or out.",
         body="What a rule says at a given moment. On Be The Puck every rule gives one of two signals: <b>IN</b> (hold the stock) or <b>OUT</b> (hold cash, earning T-bill interest)."),
    dict(slug="in-out", term="IN and OUT (the call)", topic="rules", aliases=["rule's call", "the call", "calls that changed", "call changed"],
         tip="IN means the rule holds the stock; OUT means it sits in cash earning T-bill interest.",
         body="Each rule makes a call on each stock. <b>IN</b> means the rule holds it. <b>OUT</b> means the rule has sold and is sitting in Treasury bills. The call only changes when a finished close crosses the rule's line.",
         lesson="reading-a-page#call"),
    dict(slug="next-move", term="Next move (trigger level)", topic="rules", aliases=["next move", "next-move", "trigger level", "flip level", "flip each rule", "flip it next", "would flip"],
         tip="The exact closing price that would change the rule's call at its next check.",
         body="The exact closing price that would flip a rule from IN to OUT, or OUT to IN, at its next check. It's calculated from the rule's own formula, so if the stock closes past that level, the rule changes its call. The percentage beside it shows how far the price would have to move.",
         lesson="reading-a-page#next-move"),
    dict(slug="next-check", term="Next check", topic="rules", aliases=["next check", "next checks"],
         tip="When the rule next looks at the price: after every daily close, every Friday, or the last trading day of the month.",
         body="When the rule next looks at the price. Daily rules check every close; weekly rules check Friday's close (Sunday for crypto); monthly rules check the last close of the month. Between checks the call can't change."),
    dict(slug="whipsaw", term="Whipsaw", topic="rules", aliases=["whipsaw", "whipsaws", "whipsawed", "false signal", "false signals"],
         tip="When a rule buys, then sells soon after at a lower price, because the trend it saw wasn't real. Choppy markets cause lots of them.",
         body="When a rule jumps in on a rise, then gets thrown out by a quick drop (or the reverse), losing a little each time. Sideways, choppy markets produce strings of whipsaws. Fast rules suffer them most, which is why the daily PB EMA band switches around 25 to 30 times a year on index funds.",
         lesson="trend-following#fails"),
    dict(slug="market-timing", term="Market timing", topic="rules", aliases=["market timing", "market-timing", "timing the market", "timing beat"],
         tip="Moving in and out of the market based on a forecast or rule, instead of staying invested.",
         body="Moving in and out of the market instead of staying invested. Every rule on Be The Puck except buy-and-hold is a form of market timing. Research suggests rule-based timing mostly helps in big crashes and lags in between.",
         lesson="trend-following#fails"),

    # ------------------------------------------------------------ results
    dict(slug="backtest", term="Backtest", topic="results", aliases=["backtest", "backtests", "backtested", "backtesting"],
         tip="Running a rule on past prices to see how it would have done. Useful, but the past never repeats exactly.",
         body="Running a rule on historical prices to see what it would have done. Be The Puck backtests every rule on every stock from 2005 (or the stock's first trading day), with trading costs and cash interest included. A backtest shows how a rule behaved, not what it will do next.",
         lesson="reading-a-backtest#what"),
    dict(slug="buy-and-hold", term="Buy and hold", topic="results", aliases=["buy and hold", "buy-and-hold", "buy &amp; hold", "buying and holding", "holding the stock"],
         tip="Buying and never selling. Every rule on Be The Puck is compared against simply holding the same stock.",
         body="Buy it and never sell. It's the simplest strategy and the hardest to beat, so every rule on Be The Puck is graded against buying and holding the same stock over exactly the same dates.",
         lesson="reading-a-backtest#benchmark"),
    dict(slug="benchmark", term="Benchmark", topic="results", aliases=["benchmark", "benchmarks"],
         tip="What you compare a strategy against. On Be The Puck it's buy-and-hold on the same stock.",
         body="The yardstick a strategy is measured against. On Be The Puck the benchmark is always buy-and-hold on the same stock, so a rule only 'wins' if it beats doing nothing."),
    dict(slug="annual-return", term="Annual return (CAGR)", topic="results", aliases=["annual return", "annual returns", "annualized return", "annual growth", "CAGR", "compound annual growth"],
         tip="The average yearly growth rate, compounded. 10% a year for 20 years turns $10,000 into about $67,000.",
         body="The steady yearly growth rate that would turn the starting amount into the ending amount, also called compound annual growth rate (CAGR). It's compounded, so 10% a year for 20 years turns $10,000 into about $67,000, not $30,000.",
         lesson="reading-a-backtest#return"),
    dict(slug="total-return", term="Total return", topic="results", aliases=["total return", "total returns"],
         tip="The whole gain or loss over the full period, including dividends. +300% means $10,000 became $40,000.",
         body="The full gain or loss over the whole period, dividends included. A total return of +300% means $10,000 became $40,000."),
    dict(slug="drawdown", term="Drawdown", topic="results", aliases=["worst drawdown", "drawdown", "drawdowns", "max drawdown", "maximum drawdown", "peak-to-trough"],
         tip="How far an investment fell from its highest point before recovering. A −50% drawdown means half the value was lost at the worst moment.",
         body="The drop from a peak to the lowest point before a new high. The <b>worst drawdown</b> is the biggest such drop in the whole test. It's the number that tells you how painful a strategy was to live with: a −55% drawdown means at the worst moment you'd lost more than half. Note it takes a +100% gain to recover from −50%.",
         lesson="reading-a-backtest#drawdown"),
    dict(slug="volatility", term="Volatility", topic="results", aliases=["volatility", "volatile"],
         tip="How much the price swings around, measured as the yearly standard deviation of returns. Higher means a bumpier ride.",
         body="How much returns swing around, measured as the standard deviation of daily returns scaled to a year. The S&P 500 runs at roughly 15 to 20%; a single tech stock might be 40%; Bitcoin 60% or more. Higher volatility means a bumpier ride and bigger drawdowns.",
         lesson="reading-a-backtest#risk"),
    dict(slug="sharpe-ratio", term="Sharpe ratio", topic="results", aliases=["Sharpe ratio", "Sharpe ratios", "Sharpe"],
         tip="Return earned per unit of risk taken: the return above cash, divided by volatility. Higher is better; the S&P 500 runs around 0.5.",
         body="Return per unit of risk: the return earned above cash (T-bills), divided by volatility. It lets you compare a high-return, very bumpy strategy with a lower-return, smooth one. Higher is better. Over long periods a broad stock index usually lands around 0.4 to 0.6, and anything consistently above 1 is rare.",
         lesson="reading-a-backtest#risk"),
    dict(slug="risk-adjusted", term="Risk-adjusted return", topic="results", aliases=["risk-adjusted return", "risk-adjusted returns", "risk-adjusted"],
         tip="Return judged against how much risk it took to get it, usually by the Sharpe ratio.",
         body="Return judged against the risk taken to earn it. Two strategies that each return 8% a year aren't equal if one fell 55% along the way and the other 20%. The Sharpe ratio is the usual measure.",
         lesson="reading-a-backtest#risk"),
    dict(slug="calls-right", term="Calls right (hit rate)", topic="results", aliases=["calls right", "hit rate", "win rate", "closed calls", "closed call"],
         tip="The share of a rule's finished calls that turned out right. Trend rules often win under half their calls and still come out ahead.",
         body="The share of a rule's finished calls that went the right way: an IN call is right if the price was higher by the next call, an OUT call is right if it was lower. Trend rules often score well under 50% because they take many small losses and a few large wins.",
         lesson="reading-a-backtest#calls"),
    dict(slug="switches", term="Switches per year", topic="results", aliases=["switches per year", "switches / yr", "switch in or out", "switches a year"],
         tip="How often the rule changes its call. More switches means more trading costs, more tax events and more whipsaws.",
         body="How often a rule changes its call in an average year. Monthly rules switch once or twice; fast daily rules can switch 30 times. Every switch costs money in trading costs and, in a taxable account, can trigger tax."),
    dict(slug="time-invested", term="Time invested", topic="results", aliases=["time invested", "time in the market"],
         tip="The share of days the rule was holding the stock rather than sitting in cash.",
         body="The share of days the rule held the stock. A rule invested 75% of the time spends a quarter of its life in T-bills."),
    dict(slug="trading-costs", term="Trading costs", topic="results", aliases=["trading costs", "trading cost", "trading friction", "after costs"],
         tip="What it costs to buy or sell: commissions plus the gap between buying and selling prices.",
         body="Commissions plus the bid-ask spread (the gap between what buyers pay and sellers get). Be The Puck's backtests deduct 0.05% per switch for stocks and ETFs, 0.10% for crypto and 0.30% for micro caps."),
    dict(slug="basis-point", term="Basis point", topic="results", aliases=["basis point", "basis points", "bps"],
         tip="One hundredth of a percent. 5 basis points = 0.05%.",
         body="One hundredth of one percent. 100 basis points = 1%; 5 basis points = 0.05%. Used for small numbers like trading costs and interest-rate changes."),
    dict(slug="t-bills", term="Treasury bills (T-bills)", topic="results", aliases=["T-bills", "T-bill", "Treasury bills", "Treasury bill", "T-bill interest", "T-bill yield"],
         tip="Short-term US government IOUs, treated as 'cash'. When a rule is OUT, Be The Puck assumes the money earns the T-bill rate.",
         body="Short-term loans to the US government, maturing in a year or less. They're as close to risk-free as it gets, so they stand in for 'cash'. When a rule is OUT, Be The Puck credits the money with the 13-week T-bill rate."),
    dict(slug="in-out-sample", term="In-sample and out-of-sample", topic="results", aliases=["out-of-sample", "in-sample", "out of sample"],
         tip="In-sample is the data a rule was designed on; out-of-sample is new data it never saw. Only out-of-sample results are a fair test.",
         body="In-sample data is what a rule was designed or tuned on. Out-of-sample data is history the designer never looked at. A rule that only works in-sample was probably fitted to noise.",
         lesson="reading-a-backtest#traps"),
    dict(slug="overfitting", term="Overfitting", topic="results", aliases=["overfitting", "overfit", "curve-fitting", "curve fitting", "data-mining", "data mining", "data-snooping"],
         tip="Tuning a rule so closely to past data that it captures noise, then fails on new data.",
         body="Tweaking a rule's settings until it looks great on past data. Test enough combinations and one will look brilliant by luck alone. That's why Be The Puck uses each thinker's published settings instead of picking the best-looking ones.",
         lesson="reading-a-backtest#traps"),
    dict(slug="survivorship-bias", term="Survivorship bias", topic="results", aliases=["survivorship bias", "still listed today"],
         tip="Testing only on stocks that survived to today, which makes every strategy look better than it really was.",
         body="Testing only on companies that still exist today. The ones that went bankrupt or were delisted aren't in the data, which flatters every strategy, buy-and-hold included.",
         lesson="reading-a-backtest#traps"),


    # ------------------------------------------------------------ indicators
    dict(slug="indicator", term="Indicator", topic="indicators", aliases=["indicator", "indicators", "technical indicator", "technical indicators"],
         tip="A number calculated from price (and sometimes volume) that a rule reads, such as a moving average or the RSI.",
         body="Any number calculated from past prices, and sometimes volume, that a trading rule reads to make its call. Moving averages, the RSI and the MACD are all indicators. An indicator doesn't know anything the price doesn't; it just summarises it in a particular way."),
    dict(slug="oscillator", term="Oscillator", topic="indicators", aliases=["oscillator", "oscillators"],
         tip="An indicator that swings between fixed limits, usually 0 to 100, to show when a move looks stretched.",
         body="An indicator that swings back and forth inside a fixed range, usually 0 to 100. The RSI, the stochastic, Williams %R and the Money Flow Index are oscillators. Readings near the top suggest a move is stretched upward; near the bottom, stretched downward.",
         lesson="oscillators#oscillator"),
    dict(slug="rsi", term="RSI (Relative Strength Index)", topic="indicators", aliases=["RSI", "relative strength index", "Relative Strength Index", "2-day RSI", "14-day RSI", "RSI(2)", "RSI 2"],
         tip="Welles Wilder's 0–100 gauge of how strongly a price has risen versus fallen recently. Above 70 is 'overbought', below 30 'oversold'.",
         body="J. Welles Wilder's 1978 oscillator. It compares the size of recent up days with recent down days and scales the result from 0 to 100. The usual setting is 14 days; Larry Connors uses a 2-day RSI to spot sharp short-term dips. Not related to a stock's <i>relative strength</i> against the market, despite the name.",
         lesson="oscillators#oscillator"),
    dict(slug="overbought-oversold", term="Overbought and oversold", topic="indicators", aliases=["overbought", "oversold"],
         tip="An oscillator reading near the top (overbought) or bottom (oversold) of its range: the move looks stretched, not necessarily over.",
         body="Labels for oscillator readings near the extremes of their range, such as RSI above 70 (overbought) or below 30 (oversold). They say a move looks stretched, not that it must reverse: in a strong trend a stock can stay overbought for weeks.",
         lesson="oscillators#overbought"),
    dict(slug="mean-reversion", term="Mean reversion", topic="indicators", aliases=["mean reversion", "mean-reversion", "reverts to the mean"],
         tip="The idea that a price that has moved unusually far, unusually fast, tends to snap partway back. The opposite bet to trend following.",
         body="The idea that a price stretched far from its recent average tends to move back toward it. Mean-reversion plays buy sharp dips and sell the bounce, often only inside a longer uptrend. They are right more often than trend plays, but each win is small.",
         lesson="oscillators#mean-reversion"),
    dict(slug="macd", term="MACD", topic="indicators", aliases=["MACD", "MACD line", "MACD histogram", "signal line", "signal lines"],
         tip="Gerald Appel's gap between a 12-day and a 26-day EMA. Its 9-day average is the 'signal line'; the gap between the two is the histogram.",
         body="Moving Average Convergence/Divergence, created by Gerald Appel in the late 1970s. The MACD line is the 12-day EMA minus the 26-day EMA, so it's above zero when the fast average is above the slow one. Its 9-day EMA is the <b>signal line</b>, and the difference between the two, drawn as bars, is the <b>histogram</b>.",
         lesson="momentum#rate-of-change"),
    dict(slug="rate-of-change", term="Rate of change", topic="indicators", aliases=["rate of change", "rates of change", "ROC"],
         tip="The percentage a price has moved over a set number of days or months.",
         body="How far a price has moved, in percent, over a set look-back: a 12-month rate of change of +20% means the price is 20% above where it was a year ago. Pring's KST and the Coppock curve are built from several smoothed rates of change.",
         lesson="momentum#rate-of-change"),
    dict(slug="atr", term="ATR (Average True Range)", topic="indicators", aliases=["ATR", "ATRs", "average true range", "true range"],
         tip="The average size of a day's price range, including overnight gaps. A ruler for how much a stock normally moves.",
         body="Welles Wilder's measure of how much a stock typically moves in a day. The <b>true range</b> is the day's high minus its low, stretched to include any gap from the previous close; the ATR averages it, usually over 14 or 20 days. Stops and channels set in ATRs adapt to each stock's normal volatility. The Turtles called it <b>N</b>.",
         lesson="volatility-and-stops#atr"),
    dict(slug="standard-deviation", term="Standard deviation", topic="indicators", aliases=["standard deviation", "standard deviations"],
         tip="A statistical measure of how spread out prices have been around their average.",
         body="A measure of how widely values spread around their average. For prices, a bigger standard deviation means a more volatile stretch. Bollinger Bands sit two standard deviations above and below a 20-day average.",
         lesson="volatility-and-stops#stdev"),
    dict(slug="bollinger-bands", term="Bollinger Bands", topic="indicators", aliases=["Bollinger Bands", "Bollinger band", "Bollinger bands", "upper band", "lower band"],
         tip="John Bollinger's bands two standard deviations above and below a 20-day average. They widen when prices get volatile.",
         body="John Bollinger's 1980s envelope: a 20-day simple average with bands two standard deviations above and below. The bands widen in volatile markets and squeeze together in quiet ones. Bollinger says a close outside a band usually means the move is continuing, not ending.",
         lesson="volatility-and-stops#stdev"),
    dict(slug="trailing-stop", term="Trailing stop", topic="indicators", aliases=["trailing stop", "trailing stops", "stop-loss", "stop-losses", "stop loss"],
         tip="An exit level that rises as the price rises, but never falls. It locks in part of a gain.",
         body="A sell level that follows the price up but never moves down. If the stock rises, the stop rises with it; if the stock falls back to the stop, you're out. The Chandelier Exit, Supertrend and the Turtles' 2N stop are all trailing stops. A plain <b>stop-loss</b> is a fixed exit below the entry price.",
         lesson="volatility-and-stops#trailing"),
    dict(slug="stochastic", term="Stochastic oscillator", topic="indicators", aliases=["stochastic oscillator", "stochastics", "%K", "%D", "Williams %R", "%R"],
         tip="Where today's close sits inside the last 14 days' high-low range, from 0 (the low) to 100 (the high).",
         body="Popularised by George Lane: where today's close sits within the recent high-low range, scaled 0 to 100. %K is the reading and %D its 3-day average. Larry Williams' %R is the same idea flipped upside down, from 0 to −100.",
         lesson="oscillators#oscillator"),
    dict(slug="divergence", term="Divergence", topic="indicators", aliases=["divergence", "divergences"],
         tip="When price makes a new high or low but an indicator doesn't. Often read as a sign the move is tiring.",
         body="When price and an indicator disagree, for example the price makes a new high but the RSI makes a lower high. Many indicator inventors, including Wilder, Lane and Appel, treated divergences as their strongest signals. They are hard to test mechanically, so Be The Puck's versions mostly use simpler threshold rules.",
         lesson="oscillators#overbought"),
    dict(slug="adx", term="ADX and directional movement", topic="indicators", aliases=["ADX", "directional movement", "+DI", "−DI"],
         tip="Wilder's trend-strength gauge. +DI and −DI show whether buyers or sellers are pushing harder; ADX above 25 means a strong trend.",
         body="J. Welles Wilder's system from 1978. +DI measures how far each day pushes above the previous high, −DI how far it pushes below the previous low. ADX smooths the gap between them into a 0–100 measure of trend strength: above 25 is a strong trend, below 20 no real trend."),
    dict(slug="parabolic-sar", term="Parabolic SAR", topic="indicators", aliases=["Parabolic SAR", "SAR"],
         tip="Wilder's 'stop and reverse': a stop that starts loose and speeds up as a trend runs. When price touches it, the trend is over.",
         body="Wilder's 'stop and reverse' dots. In an uptrend the SAR starts below price and moves up a little faster each time the price makes a new high. When the price falls to it, the system flips. Be The Puck holds T-bills instead of flipping short.",
         lesson="volatility-and-stops#trailing"),
    dict(slug="ichimoku", term="Ichimoku cloud", topic="indicators", aliases=["Ichimoku", "Ichimoku cloud", "Ichimoku Kinko Hyo"],
         tip="A Japanese chart system that shades a 'cloud' between two mid-points of past highs and lows, projected 26 bars ahead.",
         body="Goichi Hosoda's 'equilibrium chart at a glance', published in Japan in the late 1960s. It plots mid-points of recent highs and lows over 9, 26 and 52 bars and shades a cloud between two of them, shifted forward. Price above the cloud reads as an uptrend."),
    dict(slug="trading-volume", term="Volume", topic="indicators", aliases=["trading volume", "share volume"],
         tip="How many shares changed hands in a day. Big moves on heavy volume are taken more seriously.",
         body="The number of shares (or coins) traded in a period. Volume-based plays assume heavy buying or selling shows up in volume before it shows up fully in price.",
         lesson="volume#obv"),
    dict(slug="obv", term="On-balance volume (OBV)", topic="indicators", aliases=["on-balance volume", "On-Balance Volume", "OBV"],
         tip="Joseph Granville's running total of volume: add the day's volume on up days, subtract it on down days.",
         body="Joseph Granville's 1963 indicator. Each up day adds that day's volume to a running total and each down day subtracts it. A rising OBV suggests buyers are accumulating; Granville watched for OBV to turn before price did.",
         lesson="volume#obv"),
    dict(slug="money-flow", term="Money flow", topic="indicators", aliases=["money flow", "Chaikin Money Flow", "CMF", "Money Flow Index", "MFI"],
         tip="Volume weighted by where the price closes. Closing near the high on heavy volume counts as buying pressure.",
         body="Measures that weight volume by price action. Marc Chaikin's Money Flow weighs each day's volume by where the close lands in that day's range: near the high counts as <b>accumulation</b> (buying), near the low as <b>distribution</b> (selling). The Money Flow Index is a volume-weighted RSI.",
         lesson="volume#money-flow"),

    # ------------------------------------------------------------ patterns
    dict(slug="breakout", term="Breakout", topic="patterns", aliases=["breakout", "breakouts", "breaks out", "channel breakout"],
         tip="A close beyond the top (or bottom) of a recent range, such as a new 20-day high. Breakout plays buy it.",
         body="When the price closes beyond the edge of a recent range, for example above its highest high of the last 20 days. Breakout plays buy new highs on the theory that a stock escaping its range has started a new trend. Many breakouts fail and fall back, which is why they come with exits.",
         lesson="breakouts#breakout"),
    dict(slug="channel", term="Price channel", topic="patterns", aliases=["price channel", "price channels", "Donchian channel", "Donchian channels", "Keltner channel", "Keltner channels", "Keltner Channel"],
         tip="Lines drawn above and below price, such as the highest high and lowest low of the last 20 days. A close outside one is a signal.",
         body="A pair of lines that box in the price. A <b>Donchian channel</b> uses the highest high and lowest low of the last N days. A <b>Keltner channel</b> sits a few ATRs above and below an average. A close outside the channel is a breakout.",
         lesson="breakouts#channels"),
    dict(slug="turtles", term="The Turtles", topic="patterns", aliases=["Turtle", "Turtles", "Turtle trading", "Turtle rules"],
         tip="Traders Richard Dennis and William Eckhardt trained in 1983–84 to follow a breakout system, to settle a bet about whether trading can be taught.",
         body="In 1983 commodity traders Richard Dennis and William Eckhardt recruited about two dozen novices through newspaper ads, taught them a rule-based breakout system in two weeks and gave them money to trade. Many did very well. Their rules, published in 2003, buy 20- or 55-day breakouts and size positions by ATR.",
         lesson="breakouts#turtles"),
    dict(slug="relative-strength", term="Relative strength", topic="patterns", aliases=["relative strength", "relative-strength", "Mansfield RS", "Mansfield relative strength", "RS line"],
         tip="How a stock has done compared with the market. Not the same as the RSI.",
         body="How a stock is doing compared with something else, usually the market. Divide the stock's price by the S&amp;P 500's and you get a relative-strength line; if it's rising, the stock is beating the market. Stan Weinstein reads it from Mansfield charts. Not the same thing as the RSI.",
         lesson="momentum#relative-strength"),
    dict(slug="cross-sectional", term="Cross-sectional momentum", topic="patterns", aliases=["cross-sectional momentum", "cross-sectional", "relative momentum"],
         tip="Ranking many stocks by past return and buying the leaders. Different from asking whether one stock is rising.",
         body="Momentum measured by comparing stocks with each other: rank the market by past return and buy the leaders. Jegadeesh and Titman's 1993 study is the classic. Be The Puck tests one stock at a time, so it uses time-series versions or a comparison with SPY instead.",
         lesson="momentum#cross-sectional"),
    dict(slug="absolute-momentum", term="Absolute and dual momentum", topic="patterns", aliases=["absolute momentum", "dual momentum"],
         tip="Absolute momentum asks whether an asset beat T-bills; dual momentum also asks whether it beat the alternatives.",
         body="Gary Antonacci's terms. <b>Absolute momentum</b> holds an asset only if its own past return beat T-bills. <b>Relative momentum</b> picks the strongest of several assets. <b>Dual momentum</b> uses both.",
         lesson="momentum#relative-strength"),
    dict(slug="pullback", term="Pullback", topic="patterns", aliases=["pullback", "pullbacks"],
         tip="A short dip inside a larger uptrend. Mean-reversion plays try to buy them.",
         body="A short decline inside a longer uptrend. Larry Connors' plays buy pullbacks in stocks above their 200-day average and sell the bounce a few days later."),
    dict(slug="seasonality", term="Seasonality", topic="patterns", aliases=["seasonality", "seasonal", "calendar effect", "calendar effects"],
         tip="Patterns tied to the calendar, such as stocks doing better from November to April.",
         body="Return patterns tied to the calendar: the winter half of the year beating the summer half, the days around the turn of each month, the last days of December. Some have held up for a century; others may be luck found by searching through enough dates.",
         lesson="calendar#halloween"),
    dict(slug="exhaustion", term="Exhaustion", topic="patterns", aliases=["exhaustion", "trend exhaustion"],
         tip="The idea that a run of buying or selling eventually uses itself up. Tom DeMark's counts try to time it.",
         body="The idea that a streak of buying or selling eventually runs out of fuel. Tom DeMark's setup counts nine closes in a row below (or above) the close four days earlier as a sign the streak is spent.",
         lesson="oscillators#exhaustion"),

    # ------------------------------------------------------------ money
    dict(slug="core-satellite", term="Core and satellite", topic="money", aliases=["core and satellite", "core/satellite", "core-satellite", "sleeve"],
         tip="Keeping most of your money in a long-term 'core' and applying a rule only to a smaller 'satellite' slice.",
         body="A way to split a portfolio: a large core you simply hold, plus a smaller satellite (or sleeve) where you apply a rule or take more risk. It limits the damage if the rule goes through a bad stretch.",
         lesson="signal-to-plan#core"),
    dict(slug="position-sizing", term="Position sizing", topic="money", aliases=["position sizing", "position size", "position sizes"],
         tip="Deciding how much money goes into each holding, so no single position can do too much damage.",
         body="Deciding how much money each holding gets. A common habit is capping any single stock at a small share of the portfolio, and keeping speculative names smaller still.",
         lesson="signal-to-plan#size"),
    dict(slug="rebalancing", term="Rebalancing", topic="money", aliases=["rebalancing", "rebalance", "rebalanced"],
         tip="Bringing a portfolio back to its target mix by trimming what grew and adding to what shrank.",
         body="Resetting a portfolio to its target mix, for example back to 70% stocks and 30% bonds after stocks have run up. It forces you to trim winners and top up laggards on a schedule."),
    dict(slug="diversification", term="Diversification", topic="money", aliases=["diversification", "diversified", "diversify"],
         tip="Spreading money across many investments so one bad outcome can't sink the whole portfolio.",
         body="Spreading money across many holdings so that one company, sector or country going wrong can't sink you. An index fund is diversification in a single purchase."),
    dict(slug="leverage", term="Leverage", topic="money", aliases=["leverage", "leveraged"],
         tip="Using borrowed money (or debt inside a company) to magnify results. Gains get bigger, and so do losses.",
         body="Borrowed money that magnifies results, up and down. For an investor it means buying with borrowed funds; for a company it means carrying a lot of debt. Highly leveraged companies are the ones most likely to be wiped out in a crash."),
    dict(slug="short-selling", term="Short selling", topic="money", aliases=["short selling", "shorting", "goes short", "go short"],
         tip="Betting on a price falling by selling borrowed shares and buying them back later. Losses are unlimited if the price rises.",
         body="Selling borrowed shares in the hope of buying them back cheaper. The research version of time-series momentum goes short; Be The Puck only tests the long-only version an individual can run, which sits in T-bills instead."),
    dict(slug="tfsa", term="TFSA", topic="money", aliases=["TFSA", "TFSAs", "Tax-Free Savings Account"],
         tip="Tax-Free Savings Account (Canada): gains and withdrawals are tax-free, so switching in and out triggers no tax.",
         body="Canada's Tax-Free Savings Account. Investment growth and withdrawals are tax-free, within your contribution room. Because selling inside a TFSA creates no tax bill, it's the natural place to run a rule that switches in and out.",
         lesson="signal-to-plan#tax"),
    dict(slug="rrsp", term="RRSP", topic="money", aliases=["RRSP", "RRSPs", "Registered Retirement Savings Plan"],
         tip="Registered Retirement Savings Plan (Canada): contributions are tax-deductible and growth is tax-deferred until withdrawal.",
         body="Canada's Registered Retirement Savings Plan. Contributions reduce your taxable income and growth isn't taxed until you withdraw, so trades inside it don't create a tax bill along the way.",
         lesson="signal-to-plan#tax"),
    dict(slug="capital-gains", term="Capital gains", topic="money", aliases=["capital gains", "capital gain", "taxable disposition"],
         tip="Profit from selling an investment for more than you paid. In a regular (non-registered) account, part of it is taxable.",
         body="The profit when you sell an investment for more than you paid. In a regular, non-registered account, every sale is a taxable event, so a rule that switches often can create a lot of tax paperwork and bills.",
         lesson="signal-to-plan#tax"),
    dict(slug="superficial-loss", term="Superficial loss rule", topic="money", aliases=["superficial loss rule", "superficial loss"],
         tip="Canadian tax rule: if you sell at a loss and buy the same stock back within 30 days, you can't claim the loss yet.",
         body="A Canada Revenue Agency rule: if you sell at a loss and you (or someone affiliated with you) buy the same or identical investment within 30 days before or after, the loss is denied for now and added to the cost of the new shares. Fast rules that sell and re-buy can run into it.",
         lesson="signal-to-plan#tax"),
    dict(slug="dividend", term="Dividend", topic="money", aliases=["dividend", "dividends"],
         tip="Cash a company pays out to shareholders, usually every quarter.",
         body="Cash a company pays its shareholders, usually quarterly. Be The Puck's returns include dividends because it uses adjusted prices."),

    # ------------------------------------------------------------ desk
    dict(slug="revenue-impact", term="Revenue impact", topic="desk", aliases=["revenue impact", "revenue-impacting", "revenue impacting"],
         tip="The desk's judgement of whether a news story is likely to change how much money the company brings in.",
         body="The live desk's read on whether a news story is likely to change a company's revenue (sales). A product delay or a big new contract is revenue-impacting; a CEO interview usually isn't."),
    dict(slug="guidance", term="Guidance", topic="desk", aliases=["guidance"],
         tip="A company's own forecast of its future sales or profits. Changes to guidance often move a stock more than the actual results.",
         body="A company's own forecast for upcoming sales or profits. When a company raises or cuts guidance, the stock often moves more than it does on the actual quarter's results."),
    dict(slug="earnings-miss", term="Earnings miss", topic="desk", aliases=["earnings miss", "earnings misses"],
         tip="When a company reports profits below what analysts expected.",
         body="When reported profits come in below what analysts expected. The size of the stock's reaction depends on how much the miss changes the story and the forecasts."),
    dict(slug="batting-average", term="Batting average", topic="desk", aliases=["batting average", "batting averages"],
         tip="On the desk: the share of a source's directional calls that matched the stock's actual next-day move.",
         body="The desk's scorecard for a news source or analyst: of their stories that implied a direction, the share where the stock actually moved that way the next day. The model is graded the same way."),
    dict(slug="archetype", term="Archetype", topic="desk", aliases=["archetype", "archetypes"],
         tip="The desk's grouping of companies by how they tend to behave under stress, such as 'fortress mega-cap' or 'leveraged cyclical'.",
         body="The desk's way of grouping companies by how they tend to behave in stress, based on public facts: a fortress mega-cap with lots of cash behaves very differently in a crash from a leveraged cyclical or a micro-cap."),
    dict(slug="crash-band", term="Crash band", topic="desk", aliases=["crash band", "crash bands"],
         tip="The rough range of losses similar companies took in past crashes. Historical and approximate, not a forecast.",
         body="The approximate range of losses that companies of the same archetype suffered in past crashes, for example −60% to −90% for leveraged cyclicals in 2008. It's a historical guide, not a prediction."),
    dict(slug="dilution", term="Dilution", topic="desk", aliases=["dilution", "dilutive"],
         tip="When a company issues new shares, shrinking each existing shareholder's slice of the company.",
         body="When a company issues new shares to raise money, each existing share becomes a smaller slice of the company. Cash-burning small companies dilute often, especially after a fall."),
    dict(slug="liquidity", term="Liquidity", topic="desk", aliases=["liquidity", "illiquid"],
         tip="How easily you can buy or sell without moving the price. Big stocks are liquid; tiny ones often aren't.",
         body="How easily something can be bought or sold quickly without moving its price. Apple is very liquid. A micro cap can be illiquid: a modest order can push the price, and in a panic buyers can disappear."),
    # ------------------------------------------------------------ the business (v6)
    dict(slug="share", term="Share (stock)", topic="business", aliases=["shares outstanding"],
         tip="A slice of ownership in a company. Own one of a billion shares and you own a billionth of the business.",
         body="A slice of ownership in a company: its assets, profits and debts. Companies first sell shares to raise money; after that, shares trade between investors. <b>Shares outstanding</b> is how many slices exist.", lesson="what-is-a-stock"),
    dict(slug="ipo", term="IPO (initial public offering)", topic="business", aliases=["IPO", "IPOs", "initial public offering"],
         tip="The first time a company sells shares to the public and lists on a stock exchange.",
         body="The first sale of a company's shares to the public, when it lists on an exchange. Waves of IPOs, especially of unprofitable companies, have often come near market peaks."),
    dict(slug="eps", term="Earnings per share (EPS)", topic="business", aliases=["EPS", "earnings per share"],
         tip="A company's profit divided by its number of shares: each share's slice of the profit.",
         body="Net profit divided by the number of shares. If a company earns $1 billion and has 500 million shares, EPS is $2.", lesson="valuation"),
    dict(slug="pe-ratio", term="P/E ratio", topic="business", aliases=["P/E", "P/E ratio", "P/Es", "price-to-earnings", "price to earnings", "trailing P/E"],
         tip="Share price divided by earnings per share: how many dollars buyers pay for each dollar of yearly profit.",
         body="Price ÷ earnings per share. A P/E of 20 means paying $20 for each $1 of the last year's profit. Fast-growing or very steady companies tend to have high P/Es; slow or risky ones low P/Es. Meaningless when the company loses money.", lesson="valuation"),
    dict(slug="forward-pe", term="Forward P/E", topic="business", aliases=["forward P/E", "forward P/Es", "forward price-to-earnings"],
         tip="Price divided by analysts' estimate of next year's earnings per share.",
         body="Like the P/E, but divides by analysts' estimate of the next 12 months' profit. Lower than the trailing P/E when profits are expected to grow.", lesson="valuation"),
    dict(slug="price-to-book", term="Price to book (P/B)", topic="business", aliases=["price to book", "price-to-book", "P/B"],
         tip="Share price divided by the company's net assets per share. Most used for banks.",
         body="Price ÷ book value (equity) per share: how the market values the company against its net assets on paper. Most useful for banks and insurers."),
    dict(slug="price-to-sales", term="Price to sales", topic="business", aliases=["price to sales", "price-to-sales", "times sales"],
         tip="Market value divided by a year of revenue. Used for companies with little or no profit.",
         body="Market cap ÷ yearly revenue. Used to value companies that aren't profitable yet, where a P/E doesn't work."),
    dict(slug="profit-margin", term="Profit margin", topic="business", aliases=["profit margin", "profit margins", "operating margin"],
         tip="The share of each dollar of sales a company keeps as profit.",
         body="Profit ÷ revenue. A 20% margin means 20 cents of each dollar of sales is profit."),
    dict(slug="free-cash-flow", term="Free cash flow", topic="business", aliases=["free cash flow"],
         tip="Cash left over after running the business and paying for its investments.",
         body="Cash from operations minus capital spending. Harder to dress up than accounting profit, and what actually pays dividends and debts."),
    dict(slug="balance-sheet", term="Balance sheet", topic="business", aliases=["balance sheet", "balance sheets"],
         tip="A snapshot of what a company owns (assets) and owes (liabilities). The difference is equity.",
         body="A snapshot of what a company owns and owes. It always balances: assets = liabilities + equity.", lesson="balance-sheet"),
    dict(slug="equity", term="Equity (shareholders' equity)", topic="business", aliases=["total equity", "shareholders' equity", "negative equity", "book value"],
         tip="What a company owns minus what it owes: the shareholders' part. Negative equity means it owes more than it owns.",
         body="Assets minus liabilities: the part of the company that belongs to shareholders on paper. <b>Negative equity</b> means debts exceed assets.", lesson="balance-sheet"),
    dict(slug="debt-to-equity", term="Debt to equity", topic="business", aliases=["debt to equity", "debt-to-equity"],
         tip="Total debt divided by shareholders' equity. Above about 1.5× is heavy borrowing; above 3× is fragile.",
         body="Total debt ÷ equity. Shows how much of the business is financed by borrowing. Banks run high by design.", lesson="balance-sheet"),
    dict(slug="ebitda", term="EBITDA", topic="business", aliases=["EBITDA", "net debt to EBITDA", "net debt / EBITDA"],
         tip="Earnings before interest, taxes, depreciation and amortisation: a rough measure of operating cash earnings.",
         body="Earnings before interest, taxes, depreciation and amortisation. <b>Net debt to EBITDA</b> (debt minus cash, divided by EBITDA) is roughly how many years of operating earnings it would take to repay the debt; above 4× is stretched."),
    dict(slug="interest-cover", term="Interest cover", topic="business", aliases=["interest cover", "interest coverage"],
         tip="Operating profit divided by interest expense. Under 2× means interest could become hard to pay.",
         body="Operating profit ÷ interest. At 10× interest is easily paid; under 2×, a modest fall in profit makes the interest hard to pay.", lesson="balance-sheet"),
    dict(slug="dividend-yield", term="Dividend yield", topic="business", aliases=["dividend yield"],
         tip="A year of dividends as a percentage of the share price.",
         body="Yearly dividends per share ÷ share price. A $100 stock paying $3 a year yields 3%."),
    dict(slug="analyst-target", term="Analyst price target", topic="business", aliases=["analyst target", "analyst targets", "price target", "price targets"],
         tip="A brokerage analyst's forecast of where a stock will trade in 12 months. They lean optimistic.",
         body="A 12-month price forecast from a brokerage analyst. Useful as a summary of professional opinion, but targets lean optimistic and tend to follow the price."),
    # ------------------------------------------------------------ prices & trading (v6)
    dict(slug="candlestick", term="Candlestick", topic="prices", aliases=["candlestick", "candlesticks", "candle chart"],
         tip="A chart shape showing a period's open, high, low and close: a box for open to close, thin wicks for the high and low.",
         body="Each candle shows one period's open, high, low and close. The body spans open to close; the wicks reach the high and low. Hollow or green means it closed up; filled or red means it closed down.", lesson="candlesticks"),
    dict(slug="bid-ask", term="Bid, ask and spread", topic="prices", aliases=["bid and ask", "bid-ask spread", "best bid", "best ask", "bids and asks"],
         tip="The bid is the best price a buyer will pay, the ask the best price a seller will take; the gap is the spread.",
         body="Buyers post <b>bids</b>, sellers post <b>asks</b>. The gap between the best of each is the <b>spread</b>, a hidden cost of every trade. Thinly traded stocks have wide spreads.", lesson="how-prices-move"),
    dict(slug="order-book", term="Order book", topic="prices", aliases=["order book", "order books"],
         tip="The list of buy and sell orders waiting at each price on an exchange.",
         body="The live list of bids and asks waiting at each price. A market order takes from it; a limit order joins it.", lesson="how-prices-move"),
    dict(slug="market-limit-order", term="Market and limit orders", topic="prices", aliases=["market order", "market orders", "limit order", "limit orders"],
         tip="A market order trades now at the best available price; a limit order names your worst acceptable price and waits.",
         body="A <b>market order</b> fills immediately at whatever the order book offers. A <b>limit order</b> sets the most you'll pay or the least you'll accept, and may not fill.", lesson="how-prices-move"),
    dict(slug="cdr", term="CDR (Canadian Depositary Receipt)", topic="prices", aliases=["CDR", "CDRs", "Canadian Depositary Receipt"],
         tip="A Canadian-dollar share that tracks a U.S. stock, traded on Cboe Canada. Be The Puck shows the U.S. stock it tracks.",
         body="A Canadian-dollar security on Cboe Canada (formerly NEO) that tracks a U.S. stock, usually with currency hedging and a smaller price. Be The Puck's watchlist maps a CDR to the U.S. shares it tracks."),
    dict(slug="cap-weighted", term="Cap-weighted and equal-weight", topic="prices", aliases=["cap-weighted", "equal-weight", "equal weight", "equal-weighted"],
         tip="A cap-weighted index counts each company by its market value; an equal-weight index counts every company the same.",
         body="Most indexes are <b>cap-weighted</b>, so the biggest companies move them most. An <b>equal-weight</b> version gives every stock the same weight; when it lags, a few giants are carrying the market.", lesson="indexes"),
    dict(slug="beta", term="Beta", topic="results", aliases=["beta"],
         tip="How much a stock tends to move with the market. A beta of 2 means roughly twice the market's moves.",
         body="A measure of how much a stock moves with its benchmark index. Beta 1 moves with the market; 2 moves about twice as much; 0.5 about half. Be The Puck measures it on three years of weekly returns.", lesson="risk-and-sizing"),
    dict(slug="downside-capture", term="Downside capture", topic="results", aliases=["downside capture"],
         tip="In months the market fell, how much this stock fell on average, as a share of the market's fall.",
         body="Average return in the market's down months ÷ the market's average return in those months. 150% means it fell one and a half times as much."),
    dict(slug="crash-exposure", term="Crash exposure (the storm test)", topic="results", aliases=["crash exposure", "storm test"],
         tip="Be The Puck's storm test: a 10-point check of how hard a stock would likely be hit in a crash, from market swings, past crashes, debt and run-up.",
         body="A score out of 10 built from beta and downside capture (3 points), past crash drawdowns against the index (2), balance-sheet debt (3) and the two-year run-up (2). Low, Moderate, High or Very high. It describes fragility; it does not predict a crash."),
    dict(slug="run-up", term="Run-up", topic="results", aliases=["run-up", "run-ups", "two-year run-up"],
         tip="A big price rise over a short period. Two-year run-ups of 100%+ crashed about half the time in history.",
         body="A large rise over a short period. Greenwood, Shleifer and You found U.S. industries up 100% or more in two years fell 40% or more within the next two years about half the time, usually after rising further first."),
    # ------------------------------------------------------------ macro (v6)
    dict(slug="cape", term="CAPE (Shiller P/E)", topic="macro", aliases=["CAPE", "Shiller CAPE", "Shiller P/E", "cyclically adjusted P/E"],
         tip="The S&P 500's price divided by ten years of inflation-adjusted earnings. High readings came before poor decades.",
         body="Robert Shiller's cyclically adjusted price-to-earnings ratio: price over the ten-year average of real earnings. It has said a lot about the next ten years' returns and little about the next one."),
    dict(slug="yield-curve", term="Yield curve", topic="macro", aliases=["yield curve", "inverted yield curve", "inverted curve", "inversion"],
         tip="The gap between long- and short-term interest rates. When short rates are higher (inverted), a recession has usually followed.",
         body="The difference between long-term and short-term government bond yields. Normally long rates are higher. An <b>inverted</b> curve came before every U.S. recession since 1969, typically by 5 to 16 months."),
    dict(slug="credit-spread", term="Credit spread", topic="macro", aliases=["credit spread", "credit spreads", "high-yield spread"],
         tip="The extra interest companies pay over government bonds. Widening spreads signal lenders are getting nervous.",
         body="How much more interest corporate borrowers pay than the government. Spreads widen when lenders fear defaults; they are often tightest just before trouble."),
    dict(slug="sahm-rule", term="Sahm rule", topic="macro", aliases=["Sahm rule"],
         tip="A recession signal that triggers when the 3-month average unemployment rate rises 0.5 points above its low of the past year.",
         body="Proposed by economist Claudia Sahm in 2019. It triggered early in every U.S. recession since 1960, and fired in 2024 without one."),
    dict(slug="vix", term="VIX", topic="macro", aliases=["VIX"],
         tip="The market's 'fear gauge': how much volatility options traders expect in the S&P 500 over the next month.",
         body="Cboe's index of expected 30-day S&P 500 volatility, from option prices. Typically 12–20; it spiked above 80 in 2008 and 2020. It mostly jumps during a crash rather than before."),
    dict(slug="recession", term="Recession", topic="macro", aliases=["recession", "recessions"],
         tip="A broad fall in economic activity lasting more than a few months. In the U.S. the NBER dates them, usually months later.",
         body="A significant, widespread decline in economic activity. U.S. recessions are dated by the National Bureau of Economic Research, often long after they start."),
    dict(slug="bubble", term="Bubble", topic="macro", aliases=["bubble", "bubbles", "mania", "manias"],
         tip="Prices rising far beyond what the businesses can justify, driven by the expectation that prices will keep rising.",
         body="When prices run far ahead of what the underlying businesses can earn, pushed by the belief that they'll keep rising. Clear in hindsight, hard to call in real time.", lesson="bubbles"),
    dict(slug="margin-debt", term="Margin debt", topic="macro", aliases=["margin debt", "margin borrowing"],
         tip="Money investors borrow from brokers against their stocks. Records came near the 2000, 2007 and 2021 peaks.",
         body="Loans from brokers secured by investors' stocks. Borrowing amplifies gains and losses, and forced selling when prices fall can deepen a crash."),
    dict(slug="concentration", term="Market concentration", topic="macro", aliases=["concentration", "top-heavy"],
         tip="How much of an index sits in its biggest few companies. The S&P 500's top ten were about 38% in mid-2026.",
         body="The share of an index in its largest companies. High concentration means the index is less diversified than its name suggests.", lesson="indexes"),
]

BY_SLUG = {g["slug"]: g for g in GLOSSARY}
