"""Every play Quiplee tests: who it comes from, how it works, and its code.

A play is a published trading rule reduced to a long-or-cash switch: hold the
stock, or sit in T-bills. Rules, origins and parameters were checked against
primary or reputable secondary sources (see each analyst's sources). Where a
rule needed a choice its author never made, the choice is listed under
"assumptions" and shown on the play's page.
"""
from . import plays_fn as F

FAMILIES = [
    ("trend", "Trend following", "Hold while price stays above a moving average or trend line; step aside when it breaks."),
    ("breakout", "Breakouts & channels", "Buy when price escapes its recent range; sell when it breaks back the other way or hits a trailing stop."),
    ("momentum", "Momentum", "Own what has been rising fastest, measured by rate of change or strength against the market."),
    ("reversion", "Mean reversion", "Buy a sharp dip or an oversold reading and sell the bounce, often only inside a longer uptrend."),
    ("volume", "Volume & money flow", "Read buying and selling pressure from trading volume, not just price."),
    ("calendar", "Calendar", "Hold only in the parts of the year or month that have historically been strongest."),
]
FAMILY = {k: (name, desc) for k, name, desc in FAMILIES}
FAMILY_ORDER = [k for k, _, _ in FAMILIES]


def P(slug, name, long, family, analysts, bar, fn, short, rules, assumptions=(), origin="", **kw):
    d = dict(slug=slug, name=name, long=long, family=family, analysts=list(analysts), bar=bar, fn=fn,
             short=short, rules=list(rules), assumptions=list(assumptions), origin=origin)
    d.update(kw)
    return d


PLAYS = [
    # ------------------------------------------------------------ trend following
    P("pb-ema", "PB EMA", "PB EMA band", "trend", ["bitcoin-playboy"], "D", F.pb_ema,
      "Two exponential moving averages with a shaded band between them. Above the band is bullish, below is bearish, inside is undecided.",
      ["In when a daily close is above both EMAs.", "Out when a daily close is below both EMAs.", "Inside the band, the rule keeps its last call."],
      ["The PB EMA's lengths were never stated in its public description, and the TradingView page was taken down on 30 Sep 2026. Quiplee tests the two-EMA band with 12 and 21 days until the real lengths are confirmed."],
      "PlayBit community indicator on TradingView (published by FFriZz)", flag="Lengths unconfirmed", band=True),
    P("bull-market-support-band", "Bull Market Support Band", "Bull Market Support Band", "trend", ["benjamin-cowen"], "W", F.bmsb,
      "The 20-week simple and 21-week exponential moving averages read as one band. Bull markets tend to hold above it.",
      ["In when a weekly close is above both averages.", "Out when a weekly close is below both averages.", "Inside the band, the rule keeps its last call."],
      ["Weeks end on Friday for stocks and ETFs, and on Sunday for crypto."], "Into The Cryptoverse (Benjamin Cowen)", band=True),
    P("ripster-ema-clouds", "Ripster EMA Cloud", "Ripster 34/50 EMA Cloud", "trend", ["ripster"], "D", F.ripster,
      "The 34/50 EMA cloud that Ripster uses to set a bullish or bearish bias, tested here on the daily chart.",
      ["In when a daily close is above the 34/50 cloud.", "Out when a daily close is below the cloud.", "Inside the cloud, the rule keeps its last call."],
      ["Ripster uses several clouds and timeframes. Quiplee grades the 34/50 bias cloud on daily bars."], "Ripster EMA Clouds on TradingView", band=True),
    P("trend-template", "Trend Template", "Minervini Trend Template", "trend", ["mark-minervini"], "D", F.trend_template,
      "A seven-point checklist of moving-average and 52-week-range conditions that marks a stock in a confirmed uptrend.",
      ["In when all seven conditions pass: price above the 50, 150 and 200-day averages; 150-day above 200-day; 200-day higher than a month ago; 50-day above the 150 and 200-day; price at least 30% above its 52-week low and within 25% of its 52-week high.",
       "Out on a daily close below the 50-day average."],
      ["Minervini's eighth condition, a relative-strength rating of 70 or more, needs a full-market ranking and is left out.",
       "The template is a buy screen, not an exit system. The 50-day exit is Quiplee's assumption.", "The 52-week range uses closing prices."],
      "Trade Like a Stock Market Wizard (2013)"),
    P("stage-analysis", "Stage Analysis", "Weinstein Stage Analysis", "trend", ["stan-weinstein"], "W", F.stage,
      "The 30-week moving average splits a stock's life into four stages. Own it only in Stage 2, when price is above a rising average.",
      ["In when a weekly close is above a rising 30-week average.", "Out when a weekly close is below the 30-week average."],
      ["Rising means higher than it was four weeks earlier."], "Secrets for Profiting in Bull and Bear Markets (1988)"),
    P("mansfield-relative-strength", "Stage 2 + Mansfield RS", "Weinstein Stage 2 with Mansfield relative strength", "trend", ["stan-weinstein"], "W", F.mansfield,
      "Weinstein's two core buy conditions together: price above the 30-week average, and the stock beating the market on his Mansfield relative-strength line.",
      ["In when a weekly close is above the 30-week average and the stock's strength against SPY is above its own 52-week average.",
       "Out when either fails."],
      ["Weinstein also waits for a breakout from a base on heavy volume, which a mechanical test can't judge.",
       "Relative strength is measured against SPY. On SPY itself only the 30-week test applies."],
      "Secrets for Profiting in Bull and Bear Markets (1988); Mansfield Stock Charts", relative=True),
    P("ten-month-sma", "10-Month SMA", "Faber 10-month SMA", "trend", ["meb-faber"], "M", F.faber,
      "Check once a month. Hold the asset while its month-end price is above its 10-month average; otherwise sit in Treasury bills.",
      ["In when the month-end close is above the 10-month average.", "Out, in T-bills, when it closes below."],
      ["Signals are acted on the first trading day of the next month."], "A Quantitative Approach to Tactical Asset Allocation (2007)"),
    P("200-day-rule", "200-Day Rule", "Paul Tudor Jones's 200-day rule", "trend", ["paul-tudor-jones"], "D", F.ptj_200,
      "Stay in while the price is above its 200-day average; get out when it closes below. Jones has called the 200-day his metric for everything.",
      ["In when a daily close is above the 200-day simple average.", "Out when a daily close is below it."],
      ["Jones described a defensive exit principle, not a full system. Buying back on a close above the average is Quiplee's assumption.",
       "He is a discretionary macro trader who also sells short, so this is not his trading system."],
      "Interview in Tony Robbins' Money: Master the Game (2014)"),
    P("golden-cross", "Golden Cross", "Golden cross (50/200-day)", "trend", ["market-tradition"], "D", F.golden_cross,
      "The best-known crossover on Wall Street: own the stock while its 50-day average is above its 200-day average.",
      ["In while the 50-day average is above the 200-day (after a golden cross).", "Out while it is below (after a death cross)."],
      ["No single person invented it, so Quiplee credits market tradition."], "Market tradition; described by StockCharts and John Murphy's textbook"),
    P("granville-200-day-rules", "Granville 200-Day", "Granville's 200-day buy and sell rules", "trend", ["joseph-granville"], "D", F.granville_200,
      "Granville's first buy rule and fifth sell rule: buy when price is above a 200-day average that has stopped falling, sell when it drops below.",
      ["In when a daily close is above the 200-day average and that average is flat or higher than 20 days ago.", "Out when a daily close is below the 200-day average."],
      ["Granville described 'flattening' in words. The 20-day look-back is Quiplee's choice.",
       "His other six rules, several of them contrarian, are not tested here."],
      "A Strategy of Daily Stock Market Timing for Maximum Profit (1960); rules as restated in 1976"),
    P("hull-moving-average", "Hull Moving Average", "Hull moving average turn", "trend", ["alan-hull"], "W", F.hull_turn,
      "A fast, smooth average built to cut lag. Hull says to trade its turns, not crossovers: in while it rises, out while it falls.",
      ["In when the 16-week Hull average turns up.", "Out when it turns down."],
      ["Hull gave no set period. 16 weeks is the length he used to illustrate it."], "alanhull.com (2005)"),
    P("kaufman-adaptive-ma", "Kaufman Adaptive MA", "Kaufman adaptive moving average (KAMA)", "trend", ["perry-kaufman"], "D", F.kama_dir,
      "An average that speeds up when price moves cleanly and slows down in chop. The trend is up while it is rising.",
      ["In when KAMA (10, 2, 30) rises from the previous day.", "Out when it falls."],
      ["Kaufman also filters small turns with a volatility threshold, which is left out here."], "Smarter Trading (1995)"),
    P("tema-cross", "TEMA Crossover", "Triple EMA crossover (20/50)", "trend", ["patrick-mulloy"], "D", F.tema_cross,
      "Mulloy's triple-smoothed average removes most of an EMA's lag. Here a fast 20-day TEMA crossing a 50-day TEMA sets the call.",
      ["In when the 20-day TEMA is above the 50-day TEMA.", "Out when it is below."],
      ["Mulloy published the average, not a trading rule. The 20/50 crossover is Quiplee's convention."],
      "Technical Analysis of Stocks & Commodities, February 1994"),
    P("seykota-crossover", "Seykota 15/150", "Ed Seykota's 15/150 exponential crossover", "trend", ["ed-seykota"], "D", F.seykota,
      "The teaching system on Seykota's own site: long while a fast exponential average sits above a slow one, out otherwise. Never short.",
      ["In when the 15-day exponential average is above the 150-day.", "Out when it is below."],
      ["Seykota smooths with 1/lag, not the usual 2/(lag+1), which makes both averages slower than standard EMAs.",
       "He tested it on S&P futures with volatility-based sizing. Quiplee holds the stock fully."],
      "seykota.com Trading System Project (2003–06)", warm=1500),
    P("guppy-multiple-mas", "Guppy Multiple MAs", "Guppy multiple moving averages", "trend", ["daryl-guppy"], "D", F.gmma,
      "Twelve averages in two bundles: a fast 'trader' group and a slow 'investor' group. Own the stock when the trader group sits fully above the investors.",
      ["In when every short average (3–15 days) is above every long average (30–60 days).", "Out when the short group's average falls below the long group's."],
      ["Guppy uses the bundles to judge trend quality, not as a stand-alone signal. The strict-in, softer-out rule is Quiplee's convention."],
      "Guppy Multiple Moving Average (1990s); Trend Trading (2004)"),
    P("ichimoku-cloud", "Ichimoku Cloud", "Ichimoku cloud", "trend", ["goichi-hosoda"], "D", F.ichimoku,
      "Japan's 'one-glance' chart. Price above the cloud with the fast line over the slow line is the strong bullish reading.",
      ["In when a daily close is above the cloud and the 9-day line is above the 26-day line.", "Out when a daily close falls below the cloud.", "Inside the cloud, the rule keeps its last call."],
      ["Full Ichimoku also checks the lagging span and is used for shorts. Those parts are left out."], "Ichimoku Kinko Hyo (late 1960s)"),
    P("supertrend", "Supertrend", "Supertrend (10, 3)", "trend", ["olivier-seban"], "D", F.supertrend,
      "A line three average true ranges away from price that trails the trend. Stay in until price closes through it.",
      ["In when the Supertrend flips up (a close above the upper line).", "Out when it flips down (a close below the lower line)."],
      ["Platforms credit Olivier Seban, but no original publication could be found."], "Attributed to Olivier Seban (date unverified)", flag="Origin unverified"),
    P("williams-alligator", "Williams Alligator", "Bill Williams' Alligator", "trend", ["bill-williams"], "D", F.alligator,
      "Three shifted averages called the jaw, teeth and lips. When they fan out in order, the alligator is 'eating' and the trend is up.",
      ["In when lips are above teeth and teeth are above jaw.", "Out as soon as that order breaks."],
      ["Williams paired the Alligator with fractals and other tools and traded both ways. Only the line order is tested here."],
      "New Trading Dimensions (1998)"),
    P("vortex", "Vortex Indicator", "Vortex crossover", "trend", ["botes-siepman"], "D", F.vortex,
      "Compares how far each day reaches above the prior low against how far it reaches below the prior high. Whichever side is stronger owns the trend.",
      ["In when VI+ is above VI− (14 days).", "Out when VI− is above VI+."], [], "Technical Analysis of Stocks & Commodities, January 2010"),
    P("aroon", "Aroon", "Aroon trend", "trend", ["tushar-chande"], "D", F.aroon,
      "Measures how recently price made its 25-day high versus its 25-day low. Fresh highs mean an uptrend.",
      ["In when Aroon Up is above Aroon Down.", "Out when Aroon Down is above Aroon Up."],
      ["A stricter reading also wants Aroon Up above 70."], "Technical Analysis of Stocks & Commodities, September 1995"),
    P("parabolic-sar", "Parabolic SAR", "Wilder's Parabolic SAR", "trend", ["j-welles-wilder"], "D", F.psar,
      "A stop that starts below price and speeds up as the trend runs. When price touches it, the trend is over.",
      ["In when the SAR flips below price.", "Out when price touches the SAR from above."],
      ["Wilder's version is always in the market, flipping long to short. Quiplee holds T-bills instead of shorting.",
       "Real SAR stops fill during the day. Quiplee acts on closes."], "New Concepts in Technical Trading Systems (1978)"),
    P("adx-directional-movement", "ADX Trend", "Directional movement with ADX above 25", "trend", ["j-welles-wilder"], "D", F.dmi_adx,
      "Buy only when buyers are in control (+DI over −DI) and the trend is strong (ADX above 25). Sell when sellers take control.",
      ["In when +DI is above −DI and ADX is above 25.", "Out when +DI falls below −DI."],
      ["The ADX filter applies Wilder's own 'above 25 is a strong trend' guide as an entry gate, a common adaptation."],
      "New Concepts in Technical Trading Systems (1978)"),
    P("macd-zero-line", "MACD Zero Line", "MACD above zero", "trend", ["gerald-appel"], "D", F.macd_zero,
      "MACD above zero simply means the 12-day EMA is above the 26-day EMA: a classic fast/slow crossover.",
      ["In when MACD (12, 26) is above zero.", "Out when it is below zero."], [], "Gerald Appel, late 1970s"),
    P("zweig-four-percent", "Zweig 4% Model", "Martin Zweig's four percent model", "trend", ["martin-zweig"], "W", F.zweig,
      "Buy after a 4% weekly rise off the low; sell after a 4% weekly fall from the high. Simple, and it forces you to stay with the main trend.",
      ["In when a weekly close is 4% above the lowest weekly close since the last sell.", "Out when a weekly close is 4% below the highest weekly close since the last buy."],
      ["Zweig applied it to the Value Line index, not single stocks. A 4% band on a volatile stock will switch far more often.",
       "Some sources credit Ned Davis with first developing it."], "Winning on Wall Street (1986)"),

    # ------------------------------------------------------------ breakouts
    P("four-week-rule", "Four-Week Rule", "Donchian's four-week rule", "breakout", ["richard-donchian"], "D", F.donchian,
      "Buy when price closes above its highest high of the last four weeks; sell when it closes below the lowest low.",
      ["In when a daily close is above the prior 20-day high.", "Out when a daily close is below the prior 20-day low."],
      ["The original is always in the market, long or short, and used calendar weeks. Quiplee uses 20 trading days and holds T-bills instead of shorting."],
      "Attributed to Richard Donchian (1950s–60s)"),
    P("turtle-system-1", "Turtle System 1", "Turtle System 1 (20/10)", "breakout", ["richard-dennis-william-eckhardt"], "D", F.turtle1,
      "The Turtles' short-term system: buy a 20-day breakout, sell a 10-day low, but skip a breakout if the last one would have been a winner.",
      ["In on a close above the prior 20-day high, unless the previous breakout would have won. Then wait for a 55-day breakout instead.",
       "Out on a close below the prior 10-day low, or 2 N (two average true ranges) below the entry."],
      ["The Turtles also shorted, added up to four units and sized by volatility. Quiplee tests one long unit."], "The Original Turtle Trading Rules (1983 program, published 2003)"),
    P("turtle-system-2", "Turtle System 2", "Turtle System 2 (55/20)", "breakout", ["richard-dennis-william-eckhardt"], "D", F.turtle2,
      "The Turtles' long-term system: buy every 55-day breakout, sell a 20-day low.",
      ["In on a close above the prior 55-day high.", "Out on a close below the prior 20-day low, or 2 N below the entry."],
      ["No shorts, no adding units, signals on closes."], "The Original Turtle Trading Rules (1983 program, published 2003)"),
    P("clenow-trend-following", "Clenow Trend", "Clenow's core trend-following model", "breakout", ["andreas-clenow"], "D", F.clenow_trend,
      "The model behind Following the Trend: buy a 50-day high when the 50-day EMA is above the 100-day, then ride it with a stop three ATRs below the best close.",
      ["In on a new 50-day closing high while the 50-day EMA is above the 100-day EMA.", "Out when the close falls three average true ranges (20-day) below the highest close since entry."],
      ["Clenow trades about 50 futures markets long and short with volatility sizing. A single stock, long-only, is a big simplification.",
       "The ATR look-back is not in the book's summary; 20 days is Quiplee's choice."], "Following the Trend (2013)"),
    P("darvas-box", "Darvas Box", "Darvas box breakout", "breakout", ["nicolas-darvas"], "D", F.darvas,
      "A rising stock climbs in a stack of boxes. Buy when it breaks out of the top of a box; sell if it falls out of the bottom.",
      ["A box top is a high that isn't beaten for three days; the bottom is a low that holds for three days after that.",
       "In on a close above the box top. Out on a close below the latest box bottom, which ratchets up as new boxes form."],
      ["The three-day box rule is the usual reading of the book. Darvas also judged volume and picked stocks at new highs."],
      "How I Made $2,000,000 in the Stock Market (1960)"),
    P("keltner-channel-breakout", "Keltner Channel", "Keltner channel breakout", "breakout", ["chester-keltner", "linda-bradford-raschke"], "D", F.keltner,
      "A channel two average true ranges above and below a 20-day EMA. A close above the top says the trend has room to run.",
      ["In on a close above the upper channel (20-day EMA + 2 × 10-day ATR).", "Out on a close below the 20-day EMA."],
      ["Keltner's 1960 version used a 10-day average and the daily range. The ATR version is the modern default.",
       "Exiting at the middle line is a common modern choice, not Keltner's."], "How to Make Money in Commodities (1960); modern ATR version"),
    P("bollinger-breakout", "Bollinger Breakout", "Bollinger band breakout", "breakout", ["john-bollinger"], "D", F.bb_break,
      "Bollinger says closes outside the bands usually mean the move continues. Buy a close above the upper band; sell when price slips under the middle.",
      ["In on a close above the upper band (20-day average + 2 standard deviations).", "Out on a close below the 20-day average."],
      ["Bollinger's own breakout method starts from a 'squeeze', and he says the middle band isn't meant as a crossover line. The exit is Quiplee's choice."],
      "Bollinger on Bollinger Bands (2001)"),
    P("chandelier-exit", "Chandelier Exit", "Chandelier exit trend ride", "breakout", ["chuck-lebeau"], "D", F.chandelier,
      "LeBeau's stop hangs three average true ranges below the highest high, like a chandelier from the ceiling. Paired here with a 22-day breakout entry.",
      ["In on a close above the prior 22-day closing high.", "Out on a close below the chandelier stop (22-day high − 3 × 22-day ATR)."],
      ["The Chandelier Exit is only an exit. The breakout entry is Quiplee's pairing."], "Computer Analysis of the Futures Markets (1992); popularised by Elder (2002)"),

    # ------------------------------------------------------------ momentum
    P("time-series-momentum", "12-Month Momentum", "Time-series momentum (12-month)", "momentum", ["moskowitz-ooi-pedersen"], "M", F.tsmom,
      "Hold the asset while its return over the last 12 months beats Treasury bills. Otherwise sit in bills.",
      ["In when the 12-month return at month-end beats the 12-month T-bill return.", "Out, in T-bills, when it doesn't."],
      ["The paper also goes short. Quiplee tests the long-only version an individual investor can run."], "Journal of Financial Economics (2012)"),
    P("twelve-one-momentum", "12-1 Momentum", "12-1 momentum (single stock)", "momentum", ["jegadeesh-titman"], "M", F.mom_12_1,
      "The classic momentum measure: the return from a year ago to a month ago. Hold the stock while it is positive.",
      ["In at month-end when the return from 12 months ago to 1 month ago is above zero.", "Out when it is zero or below."],
      ["Jegadeesh and Titman ranked thousands of stocks and bought the winners. Testing one stock against zero is time-series momentum, a related idea.",
       "The skip-a-month form came later; their 1993 paper skipped at most a week."], "Journal of Finance (1993)"),
    P("dual-momentum", "Dual Momentum", "Dual momentum (stock vs SPY vs T-bills)", "momentum", ["gary-antonacci"], "M", F.dual_mom,
      "Antonacci's two tests at once: the stock must beat T-bills (absolute momentum) and beat the market (relative momentum) over 12 months.",
      ["In at month-end when the stock's 12-month return beats both T-bills and SPY.", "Out otherwise."],
      ["Antonacci applies dual momentum to whole asset classes, not single stocks, and holds bonds when out.",
       "On SPY itself only the T-bill test applies."], "Dual Momentum Investing (2014)", relative=True),
    P("stocks-on-the-move", "Stocks on the Move", "Clenow's Stocks on the Move momentum", "momentum", ["andreas-clenow"], "D", F.stocks_on_move,
      "Clenow scores momentum as the steepness of a 90-day trend line times how straight it is. Buy only when the market is above its 200-day.",
      ["In when the momentum score is positive, the stock is above its 100-day average, it hasn't moved 15% in a day in the last 90 days, and SPY is above its 200-day.",
       "Out when the score turns negative, the stock drops below its 100-day, or a 15% gap appears."],
      ["The real strategy ranks the S&P 500, buys the top fifth and rebalances weekly. 'Score above zero' is a much looser stand-in.",
       "Checked daily here rather than every Wednesday."], "Stocks on the Move (2015)", relative=True),
    P("52-week-high", "52-Week High", "52-week-high momentum", "momentum", ["george-hwang"], "M", F.high52,
      "Stocks trading near their 52-week high tend to keep going, because traders anchor on the old high. Hold while it is close.",
      ["In at month-end when the close is within 5% of its 52-week closing high.", "Out when it slips more than 15% below the high."],
      ["The paper ranks all stocks against each other. The 95% and 85% thresholds are Quiplee's choice."], "Journal of Finance (2004)"),
    P("levy-relative-strength", "Levy Relative Strength", "Levy 27-week relative strength", "momentum", ["robert-levy"], "W", F.levy,
      "One of the first academic momentum tests: own stocks trading well above their 27-week average, and stronger than the market on the same measure.",
      ["In when the weekly close is above its 27-week average and that ratio beats SPY's.", "Out when either fails."],
      ["Levy ranked a universe of stocks. Comparing with SPY stands in for the ranking."], "Journal of Finance (1967)", relative=True),
    P("macd-signal-cross", "MACD Signal Cross", "MACD signal-line crossover", "momentum", ["gerald-appel"], "D", F.macd_signal,
      "The most common MACD signal: bullish when the MACD line crosses above its 9-day signal line.",
      ["In when MACD (12, 26) is above its 9-day signal line.", "Out when it is below."],
      ["Appel also reads divergences and the zero line, which this rule ignores."], "Gerald Appel, late 1970s"),
    P("elder-impulse", "Elder Impulse", "Elder impulse system", "momentum", ["alexander-elder"], "D", F.elder_impulse,
      "Colours each day by trend (13-day EMA) and momentum (MACD histogram). Green when both rise, red when both fall.",
      ["In on a green day: the 13-day EMA and the MACD histogram both rising.", "Out on a red day: both falling. Mixed days keep the last call."],
      ["Elder uses the colours as a filter inside his Triple Screen, not as a stand-alone system."], "Come Into My Trading Room (2002)"),
    P("know-sure-thing", "Know Sure Thing", "Pring's Know Sure Thing (KST)", "momentum", ["martin-pring"], "D", F.kst,
      "Four smoothed rates of change, weighted and added together. When the KST crosses above its signal line, momentum is turning up.",
      ["In when the KST is above its 9-day signal line.", "Out when it is below."],
      ["Pring preferred weekly and monthly KST for the main trend. The daily version is a shorter-term reading."],
      "Technical Analysis of Stocks & Commodities, September 1992"),
    P("coppock-curve", "Coppock Curve", "Coppock curve", "momentum", ["edwin-coppock"], "M", F.coppock,
      "A monthly momentum line built to spot the end of bear markets. The buy signal is the curve turning up from below zero.",
      ["In at month-end when the curve, below zero, turns up.", "Out when it is below zero and falling."],
      ["Coppock only defined the buy. The exit is Quiplee's addition.", "He designed it for broad indexes, not single stocks."],
      "Barron's (1962, some sources say 1965)"),
    P("cci-100", "CCI +100", "Lambert's CCI breakout", "momentum", ["donald-lambert"], "D", F.cci100,
      "The Commodity Channel Index measures how far price has run from its average. Lambert bought above +100 and sold when it fell back.",
      ["In when the CCI (20) crosses above +100.", "Out when it crosses back below +100."],
      ["The original also sells short below −100."], "Commodities magazine (1980)"),

    # ------------------------------------------------------------ mean reversion
    P("rsi-30-70", "RSI 30/70", "RSI 30/70 crossover", "reversion", ["j-welles-wilder"], "D", F.rsi_30_70,
      "The textbook use of Wilder's RSI: buy when it climbs back above 30 (oversold), sell when it drops back below 70 (overbought).",
      ["In when the 14-day RSI crosses up through 30.", "Out when it crosses down through 70."],
      ["Wilder treated failure swings and divergences as stronger signals. The 30/70 cross is a popular simplification.",
       "There is no stop: the rule can hold through a long decline."], "New Concepts in Technical Trading Systems (1978)"),
    P("rsi-2-pullback", "RSI(2) Pullback", "Connors RSI(2) pullback", "reversion", ["larry-connors", "cesar-alvarez"], "D", F.rsi2,
      "Buy a sharp short-term dip, but only in a long-term uptrend, and sell the first bounce.",
      ["In when the stock is above its 200-day average and the 2-day RSI is below 10.", "Out on a close above the 5-day average."],
      ["Connors buys on the signal day's close, as Quiplee does. No stop-loss, as in the book."], "Short Term Trading Strategies That Work (2008)"),
    P("double-7s", "Double 7s", "Connors & Alvarez Double 7s", "reversion", ["larry-connors", "cesar-alvarez"], "D", F.double7,
      "Above the 200-day average, buy a close at a 7-day low and sell a close at a 7-day high.",
      ["In when the stock is above its 200-day average and closes at its lowest close of the last 7 days.", "Out when it closes at its highest close of the last 7 days."],
      ["Tested by the authors on ETFs. Single stocks are an extension."], "Short Term Trading Strategies That Work (2008)"),
    P("bollinger-reversion", "Bollinger Reversion", "Bollinger band reversion", "reversion", ["john-bollinger"], "D", F.bb_revert,
      "A common way traders use the bands, not Bollinger's own: buy a close below the lower band, sell when price gets back to the middle.",
      ["In on a close below the lower band (20-day average − 2 standard deviations).", "Out on a close above the 20-day average."],
      ["This runs against Bollinger's advice that tags of the bands are not signals. It is shown because so many traders use it."],
      "Trader practice using Bollinger Bands"),
    P("stochastic-20-80", "Stochastic 20/80", "Stochastic 20/80 crossover", "reversion", ["george-lane"], "D", F.stochastic,
      "Where today's close sits in the last 14 days' range. Buy a %K/%D cross up in the oversold zone, sell a cross down in the overbought zone.",
      ["In when %K crosses above %D while %D is below 20.", "Out when %K crosses below %D while %D is above 80."],
      ["Lane said divergence was the only signal that matters. The zone cross is the textbook simplification."], "Lane's Stochastics, Stocks & Commodities (1984)"),
    P("williams-percent-r", "Williams %R", "Williams %R −80/−20", "reversion", ["larry-williams"], "D", F.willr,
      "The stochastic turned upside down: 0 is the top of the 14-day range, −100 the bottom. Buy out of oversold, sell out of overbought.",
      ["In when %R crosses up through −80.", "Out when it crosses down through −20."],
      ["Williams read %R differently in bull, bear and sideways markets. This is the modern charting convention."],
      "How I Made One Million Dollars Last Year Trading Commodities (1973)"),
    P("demark-setup-9", "DeMark 9-Count", "DeMark 9-count setup", "reversion", ["tom-demark"], "D", F.demark9,
      "Count closes below the close four days earlier. Nine in a row marks a selling streak that is likely spent.",
      ["In when a buy setup completes: 9 straight closes below the close 4 days earlier.", "Out when a sell setup completes: 9 straight closes above it."],
      ["DeMark's full Sequential waits for a 13-bar countdown and other qualifiers. The bare 9-count is a popular shortcut.",
       "TD Sequential is a trademark of DeMark Analytics."], "The New Science of Technical Analysis (1994)"),
    P("mayer-multiple", "Mayer Multiple", "Mayer Multiple below 2.4", "reversion", ["trace-mayer"], "D", F.mayer,
      "Price divided by its 200-day average. Mayer found buying bitcoin below 2.4 worked best; above that was bubble territory.",
      ["In while the close is less than 2.4 times its 200-day average.", "Out when it reaches 2.4 or more."],
      ["Mayer used it to decide when to keep buying, not when to sell. Selling above 2.4 is Quiplee's reading.",
       "On ordinary stocks a price 2.4 times the 200-day is rare, so this is close to buy and hold."], "Bitcoin Knowledge (around 2017)"),

    # ------------------------------------------------------------ volume
    P("on-balance-volume", "On-Balance Volume", "Granville's on-balance volume trend", "volume", ["joseph-granville"], "D", F.obv,
      "A running total of volume: add it on up days, subtract it on down days. Rising OBV says buyers are accumulating.",
      ["In when OBV is above its 20-day average.", "Out when it is below."],
      ["The OBV is Granville's; the 20-day signal line is Quiplee's. He read OBV's trend and divergences by eye."],
      "Granville's New Key to Stock Market Profits (1963)"),
    P("chaikin-money-flow", "Chaikin Money Flow", "Chaikin money flow", "volume", ["marc-chaikin"], "D", F.cmf,
      "Weighs each day's volume by where the close lands in the day's range. Positive means buying pressure.",
      ["In when the 21-day CMF rises above +0.05.", "Out when it falls below −0.05. In between, the rule keeps its last call."],
      ["The ±0.05 buffer is StockCharts' suggested filter against whipsaws."], "Marc Chaikin (date unverified)"),
    P("money-flow-index", "Money Flow Index", "Money Flow Index 20/80", "volume", ["quong-soudack"], "D", F.mfi,
      "RSI with volume added. Buy when it climbs out of oversold (20), sell when it drops out of overbought (80).",
      ["In when the 14-day MFI crosses up through 20.", "Out when it crosses down through 80."],
      ["The creators also stress divergences, which this rule ignores."], "Technical Analysis of Stocks & Commodities, March 1989"),

    # ------------------------------------------------------------ calendar
    P("halloween-indicator", "Halloween Indicator", "Halloween indicator (sell in May)", "calendar", ["bouman-jacobsen", "yale-jeffrey-hirsch"], "D", F.halloween,
      "Own stocks from November through April; sit in T-bills from May through October.",
      ["In at the close on the last trading day of October.", "Out at the close on the last trading day of April."],
      ["The research used market indexes. Applying it to one stock assumes the season carries over."], "American Economic Review (2002); Stock Trader's Almanac (1986)",
      calendar=True),
    P("best-six-months-macd", "Best Six + MACD", "Almanac Best Six Months with MACD timing", "calendar", ["yale-jeffrey-hirsch"], "D", F.best_six_macd,
      "The Almanac's refinement of the Best Six Months: wait for a MACD buy signal from October 1, and a MACD sell signal from April 1.",
      ["In on the first MACD (8, 17, 9) cross above its signal line on or after October 1.", "Out on the first cross below on or after April 1."],
      ["The Almanac requires the Dow, S&P 500 and Nasdaq to agree. Quiplee applies the MACD to the stock itself.",
       "The sell-side MACD settings are not published; 8, 17, 9 is assumed."], "Stock Trader's Almanac",
      season=((10, 1), (4, 1))),
    P("seasonal-timing-strategy", "Seasonal Timing", "Sy Harding's Seasonal Timing Strategy", "calendar", ["sy-harding"], "D", F.harding,
      "Enter around October 16 and exit around April 20, but let MACD shift each date: wait for a buy signal if it isn't on one, and hold for a sell signal if it isn't.",
      ["From October 16, in on the first day MACD is above its signal line.", "From April 20, out on the first day MACD is below it."],
      ["Harding applied it to the Dow. His MACD settings were never published; 12, 26, 9 is assumed."], "Street Smart Report (1999)",
      season=((10, 16), (4, 20))),
    P("santa-claus-rally", "Santa Claus Rally", "Santa Claus rally", "calendar", ["yale-jeffrey-hirsch"], "D", F.santa,
      "The last five trading days of December and the first two of January. That's it: seven days a year.",
      ["In at the close six trading days before year-end.", "Out at the close on the second trading day of January."],
      ["Hirsch described a market tendency, not a stand-alone system for single stocks."], "Stock Trader's Almanac (defined 1972)", calendar=True),
    P("turn-of-the-month", "Turn of the Month", "Turn-of-the-month effect", "calendar", ["lakonishok-smidt", "robert-ariel"], "D", F.turn_of_month,
      "Returns bunch up around the start of each month. Hold for four trading days: the last day of a month and the first three of the next.",
      ["In at the close two trading days before month-end.", "Out at the close on the third trading day of the new month."],
      ["The studies measured index returns, not single stocks, and were descriptive rather than trading systems."],
      "Journal of Financial Economics (1987); Review of Financial Studies (1988)", calendar=True),

    # ------------------------------------------------------------ benchmark
    P("buy-and-hold", "Buy & Hold", "Buy and hold (benchmark)", "benchmark", ["john-bogle"], "D", F.hold,
      "Own it and never sell. Every other play on Quiplee is graded against this one.", ["Always in."], [], "", benchmark=True),
]

PLAY = {p["slug"]: p for p in PLAYS}
TIMED = [p for p in PLAYS if not p.get("benchmark")]
BAR_WORD = {"D": "daily", "W": "weekly", "M": "month-end"}


def by_family():
    return [(k, FAMILY[k][0], [p for p in TIMED if p["family"] == k]) for k in FAMILY_ORDER]
