"""Every play Be The Puck tests: who it comes from, how it works, and its code.

A play is a published trading rule reduced to a long-or-cash switch: hold the
stock, or sit in T-bills. Rules, origins and parameters were checked against
primary or reputable secondary sources (see each analyst's sources). Where a
rule needed a choice its author never made, the choice is listed under
"assumptions" and shown on the play's page.
"""
from . import plays_fn as F
from . import plays_fn_mr as FM, plays_fn_tb as FT, plays_fn_vcp as FV  # the plays added in October 2026

FAMILIES = [
    ("trend", "Trend following", "Hold while price stays above a moving average or trend line; step aside when it breaks."),
    ("breakout", "Breakouts & channels", "Buy when price escapes its recent range; sell when it breaks back the other way or hits a trailing stop."),
    ("momentum", "Momentum", "Own what has been rising fastest, measured by rate of change or strength against the market."),
    ("reversion", "Mean reversion", "Buy a sharp dip or an oversold reading and sell the bounce, often only inside a longer uptrend."),
    ("volume", "Volume & money flow", "Read buying and selling pressure from trading volume, not just price."),
    ("pattern", "Candles & chart patterns", "Read short-term price patterns, like candlesticks and failed breakouts, as signs a move is turning."),
    ("calendar", "Calendar", "Hold only in the parts of the year or month that have historically been strongest."),
]
FAMILY = {k: (name, desc) for k, name, desc in FAMILIES}
FAMILY_ORDER = [k for k, _, _ in FAMILIES]


def P(slug, name, long, family, analysts, bar, fn, short, rules, assumptions=(), origin="", **kw):
    d = dict(slug=slug, name=name, long=long, family=family, analysts=list(analysts), bar=bar, fn=fn,
             short=short, rules=list(rules), assumptions=list(assumptions), origin=origin)
    d.update(kw)
    return d


PLAYS = [
    # ------------------------------------------------------------ trend following
    P("pb-ema", "PB EMA", "PB EMA band", "trend", ["bitcoin-playboy"], "D", F.pb_ema,
      "Two exponential moving averages with a shaded band between them. Above the band is bullish, below is bearish, inside is undecided.",
      ["In when a daily close is above both EMAs.", "Out when a daily close is below both EMAs.", "Inside the band, the rule keeps its last call."],
      ["The PB EMA's lengths were never stated in its public description, and the TradingView page was taken down on 30 Sep 2026. Be The Puck tests the two-EMA band with 12 and 21 days until the real lengths are confirmed."],
      "PlayBit community indicator on TradingView (published by FFriZz)", flag="Lengths unconfirmed", band=True),
    P("bull-market-support-band", "Bull Market Support Band", "Bull Market Support Band", "trend", ["benjamin-cowen"], "W", F.bmsb,
      "The 20-week simple and 21-week exponential moving averages read as one band. Bull markets tend to hold above it.",
      ["In when a weekly close is above both averages.", "Out when a weekly close is below both averages.", "Inside the band, the rule keeps its last call."],
      ["Weeks end on Friday for stocks and ETFs, and on Sunday for crypto."], "Into The Cryptoverse (Benjamin Cowen)", band=True),
    P("ripster-ema-clouds", "Ripster EMA Cloud", "Ripster 34/50 EMA Cloud", "trend", ["ripster"], "D", F.ripster,
      "The 34/50 EMA cloud that Ripster uses to set a bullish or bearish bias, tested here on the daily chart.",
      ["In when a daily close is above the 34/50 cloud.", "Out when a daily close is below the cloud.", "Inside the cloud, the rule keeps its last call."],
      ["Ripster uses several clouds and timeframes. Be The Puck grades the 34/50 bias cloud on daily bars."], "Ripster EMA Clouds on TradingView", band=True),
    P("trend-template", "Trend Template", "Minervini Trend Template", "trend", ["mark-minervini"], "D", F.trend_template,
      "A seven-point checklist of moving-average and 52-week-range conditions that marks a stock in a confirmed uptrend.",
      ["In when all seven conditions pass: price above the 50, 150 and 200-day averages; 150-day above 200-day; 200-day higher than a month ago; 50-day above the 150 and 200-day; price at least 30% above its 52-week low and within 25% of its 52-week high.",
       "Out on a daily close below the 50-day average."],
      ["Minervini's eighth condition, a relative-strength rating of 70 or more, needs a full-market ranking and is left out.",
       "The template is a buy screen, not an exit system. The 50-day exit is Be The Puck's assumption.", "The 52-week range uses closing prices."],
      "Trade Like a Stock Market Wizard (2013)"),
    P("stage-analysis", "Stage Analysis", "Weinstein Stage Analysis", "trend", ["stan-weinstein"], "W", F.stage,
      "The 30-week moving average splits a stock's life into four stages. Own it only in Stage 2, when price is above a rising average.",
      ["In when a weekly close is above a rising 30-week average.", "Out when a weekly close is below the 30-week average."],
      ["Rising means higher than it was four weeks earlier."], "Secrets for Profiting in Bull and Bear Markets (1988)"),
    P("mansfield-relative-strength", "Stage 2 + Mansfield RS", "Weinstein Stage 2 with Mansfield relative strength", "trend", ["stan-weinstein"], "W", F.mansfield,
      "Weinstein's two core buy conditions together: price above the 30-week average, and the stock beating the market on his Mansfield relative-strength line.",
      ["In when a weekly close is above the 30-week average and the stock's strength against SPY is above its own 52-week average.",
       "Out when either fails."],
      ["Weinstein also waits for a breakout from a base on heavy volume, which a mechanical test can't judge.",
       "Relative strength is measured against SPY. On SPY itself only the 30-week test applies."],
      "Secrets for Profiting in Bull and Bear Markets (1988); Mansfield Stock Charts", relative=True),
    P("ten-month-sma", "10-Month SMA", "Faber 10-month SMA", "trend", ["meb-faber"], "M", F.faber,
      "Check once a month. Hold the asset while its month-end price is above its 10-month average; otherwise sit in Treasury bills.",
      ["In when the month-end close is above the 10-month average.", "Out, in T-bills, when it closes below."],
      ["Signals are acted on the first trading day of the next month."], "A Quantitative Approach to Tactical Asset Allocation (2007)"),
    P("200-day-rule", "200-Day Rule", "Paul Tudor Jones's 200-day rule", "trend", ["paul-tudor-jones"], "D", F.ptj_200,
      "Stay in while the price is above its 200-day average; get out when it closes below. Jones has called the 200-day his metric for everything.",
      ["In when a daily close is above the 200-day simple average.", "Out when a daily close is below it."],
      ["Jones described a defensive exit principle, not a full system. Buying back on a close above the average is Be The Puck's assumption.",
       "He is a discretionary macro trader who also sells short, so this is not his trading system."],
      "Interview in Tony Robbins' Money: Master the Game (2014)"),
    P("golden-cross", "Golden Cross", "Golden cross (50/200-day)", "trend", ["market-tradition"], "D", F.golden_cross,
      "The best-known crossover on Wall Street: own the stock while its 50-day average is above its 200-day average.",
      ["In while the 50-day average is above the 200-day (after a golden cross).", "Out while it is below (after a death cross)."],
      ["No single person invented it, so Be The Puck credits market tradition."], "Market tradition; described by StockCharts and John Murphy's textbook"),
    P("granville-200-day-rules", "Granville 200-Day", "Granville's 200-day buy and sell rules", "trend", ["joseph-granville"], "D", F.granville_200,
      "Granville's first buy rule and fifth sell rule: buy when price is above a 200-day average that has stopped falling, sell when it drops below.",
      ["In when a daily close is above the 200-day average and that average is flat or higher than 20 days ago.", "Out when a daily close is below the 200-day average."],
      ["Granville described 'flattening' in words. The 20-day look-back is Be The Puck's choice.",
       "His other six rules, several of them contrarian, are not tested here."],
      "A Strategy of Daily Stock Market Timing for Maximum Profit (1960); rules as restated in 1976"),
    P("hull-moving-average", "Hull Moving Average", "Hull moving average turn", "trend", ["alan-hull"], "W", F.hull_turn,
      "A fast, smooth average built to cut lag. Hull says to trade its turns, not crossovers: in while it rises, out while it falls.",
      ["In when the 16-week Hull average turns up.", "Out when it turns down."],
      ["Hull gave no set period. 16 weeks is the length he used to illustrate it."], "alanhull.com (2005)"),
    P("kaufman-adaptive-ma", "Kaufman Adaptive MA", "Kaufman adaptive moving average (KAMA)", "trend", ["perry-kaufman"], "D", F.kama_dir,
      "An average that speeds up when price moves cleanly and slows down in chop. The trend is up while it is rising.",
      ["In when KAMA (10, 2, 30) rises from the previous day.", "Out when it falls."],
      ["Kaufman also filters small turns with a volatility threshold, which is left out here."], "Smarter Trading (1995)"),
    P("tema-cross", "TEMA Crossover", "Triple EMA crossover (20/50)", "trend", ["patrick-mulloy"], "D", F.tema_cross,
      "Mulloy's triple-smoothed average removes most of an EMA's lag. Here a fast 20-day TEMA crossing a 50-day TEMA sets the call.",
      ["In when the 20-day TEMA is above the 50-day TEMA.", "Out when it is below."],
      ["Mulloy published the average, not a trading rule. The 20/50 crossover is Be The Puck's convention."],
      "Technical Analysis of Stocks & Commodities, February 1994"),
    P("seykota-crossover", "Seykota 15/150", "Ed Seykota's 15/150 exponential crossover", "trend", ["ed-seykota"], "D", F.seykota,
      "The teaching system on Seykota's own site: long while a fast exponential average sits above a slow one, out otherwise. Never short.",
      ["In when the 15-day exponential average is above the 150-day.", "Out when it is below."],
      ["Seykota smooths with 1/lag, not the usual 2/(lag+1), which makes both averages slower than standard EMAs.",
       "He tested it on S&P futures with volatility-based sizing. Be The Puck holds the stock fully."],
      "seykota.com Trading System Project (2003–06)", warm=1500),
    P("guppy-multiple-mas", "Guppy Multiple MAs", "Guppy multiple moving averages", "trend", ["daryl-guppy"], "D", F.gmma,
      "Twelve averages in two bundles: a fast 'trader' group and a slow 'investor' group. Own the stock when the trader group sits fully above the investors.",
      ["In when every short average (3–15 days) is above every long average (30–60 days).", "Out when the short group's average falls below the long group's."],
      ["Guppy uses the bundles to judge trend quality, not as a stand-alone signal. The strict-in, softer-out rule is Be The Puck's convention."],
      "Guppy Multiple Moving Average (1990s); Trend Trading (2004)"),
    P("ichimoku-cloud", "Ichimoku Cloud", "Ichimoku cloud", "trend", ["goichi-hosoda"], "D", F.ichimoku,
      "Japan's 'one-glance' chart. Price above the cloud with the fast line over the slow line is the strong bullish reading.",
      ["In when a daily close is above the cloud and the 9-day line is above the 26-day line.", "Out when a daily close falls below the cloud.", "Inside the cloud, the rule keeps its last call."],
      ["Full Ichimoku also checks the lagging span and is used for shorts. Those parts are left out."], "Ichimoku Kinko Hyo (late 1960s)"),
    P("supertrend", "Supertrend", "Supertrend (10, 3)", "trend", ["olivier-seban"], "D", F.supertrend,
      "A line three average true ranges away from price that trails the trend. Stay in until price closes through it.",
      ["In when the Supertrend flips up (a close above the upper line).", "Out when it flips down (a close below the lower line)."],
      ["Platforms credit Olivier Seban, but no original publication could be found."], "Attributed to Olivier Seban (date unverified)", flag="Origin unverified"),
    P("williams-alligator", "Williams Alligator", "Bill Williams' Alligator", "trend", ["bill-williams"], "D", F.alligator,
      "Three shifted averages called the jaw, teeth and lips. When they fan out in order, the alligator is 'eating' and the trend is up.",
      ["In when lips are above teeth and teeth are above jaw.", "Out as soon as that order breaks."],
      ["Williams paired the Alligator with fractals and other tools and traded both ways. Only the line order is tested here."],
      "New Trading Dimensions (1998)"),
    P("vortex", "Vortex Indicator", "Vortex crossover", "trend", ["botes-siepman"], "D", F.vortex,
      "Compares how far each day reaches above the prior low against how far it reaches below the prior high. Whichever side is stronger owns the trend.",
      ["In when VI+ is above VI− (14 days).", "Out when VI− is above VI+."], [], "Technical Analysis of Stocks & Commodities, January 2010"),
    P("aroon", "Aroon", "Aroon trend", "trend", ["tushar-chande"], "D", F.aroon,
      "Measures how recently price made its 25-day high versus its 25-day low. Fresh highs mean an uptrend.",
      ["In when Aroon Up is above Aroon Down.", "Out when Aroon Down is above Aroon Up."],
      ["A stricter reading also wants Aroon Up above 70."], "Technical Analysis of Stocks & Commodities, September 1995"),
    P("parabolic-sar", "Parabolic SAR", "Wilder's Parabolic SAR", "trend", ["j-welles-wilder"], "D", F.psar,
      "A stop that starts below price and speeds up as the trend runs. When price touches it, the trend is over.",
      ["In when the SAR flips below price.", "Out when price touches the SAR from above."],
      ["Wilder's version is always in the market, flipping long to short. Be The Puck holds T-bills instead of shorting.",
       "Real SAR stops fill during the day. Be The Puck acts on closes."], "New Concepts in Technical Trading Systems (1978)"),
    P("adx-directional-movement", "ADX Trend", "Directional movement with ADX above 25", "trend", ["j-welles-wilder"], "D", F.dmi_adx,
      "Buy only when buyers are in control (+DI over −DI) and the trend is strong (ADX above 25). Sell when sellers take control.",
      ["In when +DI is above −DI and ADX is above 25.", "Out when +DI falls below −DI."],
      ["The ADX filter applies Wilder's own 'above 25 is a strong trend' guide as an entry gate, a common adaptation."],
      "New Concepts in Technical Trading Systems (1978)"),
    P("macd-zero-line", "MACD Zero Line", "MACD above zero", "trend", ["gerald-appel"], "D", F.macd_zero,
      "MACD above zero simply means the 12-day EMA is above the 26-day EMA: a classic fast/slow crossover.",
      ["In when MACD (12, 26) is above zero.", "Out when it is below zero."], [], "Gerald Appel, late 1970s"),
    P("zweig-four-percent", "Zweig 4% Model", "Martin Zweig's four percent model", "trend", ["martin-zweig"], "W", F.zweig,
      "Buy after a 4% weekly rise off the low; sell after a 4% weekly fall from the high. Simple, and it forces you to stay with the main trend.",
      ["In when a weekly close is 4% above the lowest weekly close since the last sell.", "Out when a weekly close is 4% below the highest weekly close since the last buy."],
      ["Zweig applied it to the Value Line index, not single stocks. A 4% band on a volatile stock will switch far more often.",
       "Some sources credit Ned Davis with first developing it."], "Winning on Wall Street (1986)"),

    P("ehlers-mama-fama", "MAMA/FAMA Cross", "Ehlers' MESA Adaptive Moving Average (MAMA/FAMA) crossover", "trend", ["john-ehlers"], "D", FT.ehlers_mama,
      "MAMA is an average that speeds up or slows down with the market's measured cycle. Hold the stock while it sits above its slower companion line, FAMA.",
      ["In while MAMA is above FAMA.", "Out while MAMA is below FAMA."],
      ["Both lines use the midpoint of each day's high and low, with Ehlers' published speed limits of 0.5 and 0.05. FAMA moves at half MAMA's speed.",
       "Ehlers' code starts every running value at zero. Be The Puck starts both lines at the first price and ignores the first 60 days.",
       "Ehlers' own test on 100 stocks was long only, as here. His paper doesn't say how fills were timed; Be The Puck acts on the signal day's close."],
      "MAMA: The Mother of Adaptive Moving Averages, adapted from Rocket Science for Traders (2001)",
      sources=[("Ehlers, MAMA - The Mother of Adaptive Moving Averages (PDF with EasyLanguage code)", "https://www.mesasoftware.com/papers/MAMA.pdf")]),
    P("schaff-trend-cycle", "Schaff Trend Cycle", "Schaff Trend Cycle 25/75 setup and trigger", "trend", ["doug-schaff"], "D", FT.schaff_stc,
      "A MACD line run twice through a stochastic, so it swings between 0 and 100 like a cycle. A turn up from below 25 sets up a buy; a turn down from above 75 sets up a sell.",
      ["Buy setup: the Schaff Trend Cycle (STC, settings 10, 23, 50) turns up from below 25. In when a later close is above that setup day's high.",
       "Sell setup: the STC turns down from above 75. Out when a later close is below that setup day's low.",
       "A new setup the other way cancels a pending one. Otherwise the rule keeps its last call."],
      ["Schaff lets the trigger be a trade through the setup day or a close beyond it. Be The Puck uses the close.",
       "'Turns up' means today's STC is above yesterday's after yesterday's was no higher than the day before (mirror for 'turns down'). Schaff describes the turn but gives no exact test.",
       "Schaff's defaults (cycle 10, averages of 23 and 50 days, smoothing 0.5) are used on daily bars. He built the indicator for currencies."],
      "Schaff Trend Cycle code (1999), released by Doug Schaff in 2008; Catching Currency Moves with the Schaff Trend Cycle Indicator (2002)",
      sources=[("Doug Schaff, Releasing the Code to the Schaff Trend Cycle (2008, PDF)", "https://c.mql5.com/forextsd/forum/40/schaff_code.pdf"),
               ("Doug Schaff, Catching Currency Moves with the Schaff Trend Cycle Indicator (2002, PDF)", "https://c.mql5.com/forextsd/forum/153/schaff_trend_cycle.pdf"),
               ("LuxAlgo Library: Schaff Trend Cycle", "https://www.luxalgo.com/library/concept/schaff-trend-cycle.md")]),
    P("ehlers-zero-lag", "Zero Lag EC Cross", "Ehlers and Way's Zero Lag (error-correcting EMA) crossover", "trend", ["john-ehlers", "ric-way"], "D", FT.ehlers_zero_lag,
      "An exponential average with an error-correcting term that pulls it toward price and removes most of the lag. Buy when it crosses above the ordinary average, but ignore crossings where the corrected line is hugging the price.",
      ["In when the error-corrected line crosses above the 32-day EMA while it sits more than 0.75% away from the close.",
       "Out when it crosses below the EMA with the same 0.75% test.",
       "Crossings that fail the test are ignored, and the rule keeps its last call."],
      ["The settings are the ones from the authors' Microsoft test (length 32, gain limit 22, threshold 0.75), not the code defaults (20, 50, 1). The authors note that a large gain limit just makes the line track the close.",
       "The published strategy goes short on the sell signal. Be The Puck holds T-bills instead.",
       "The strategy buys at the next day's open. Be The Puck acts on the signal day's close."],
      "Zero Lag (Well, Almost), Technical Analysis of Stocks & Commodities, November 2010",
      sources=[("Ehlers & Way, Zero Lag (Well, Almost) (PDF with strategy code)", "https://www.mesasoftware.com/papers/ZeroLag.pdf"),
               ("Stocks & Commodities V.28:11 (30-35): Zero Lag (Well, Almost)", "https://store.traders.com/stcov283zela.html")],
      warm=800),
    P("decisionpoint-ittm", "DP Trend Model", "DecisionPoint Intermediate-Term Trend Model (20/50-day EMA)", "trend", ["carl-swenlin", "erin-swenlin"], "D", FT.dp_ittm,
      "DecisionPoint's intermediate-term trend signal is a BUY while the 20-day EMA is above the 50-day EMA. A cross back down is Neutral in a bull market and a Sell in a bear market; both mean cash here.",
      ["In when the 20-day EMA is above the 50-day EMA (a DecisionPoint BUY).",
       "Out when the 20-day EMA is below the 50-day EMA, whether DecisionPoint calls it Neutral (50-day above the 200-day) or Sell (50-day below the 200-day)."],
      ["DecisionPoint's Neutral means out of the market or hedged, so it is treated as cash.",
       "Standard exponential averages of daily closes. DecisionPoint's extra notes on price against the averages are left out."],
      "DecisionPoint (Carl Swenlin); documented in StockCharts ChartSchool and Erin Swenlin's DecisionPoint articles (2015 to 2016)",
      sources=[("StockCharts ChartSchool: DecisionPoint Trend Model", "https://chartschool.stockcharts.com/table-of-contents/trading-strategies-and-models/decisionpoint-trend-model"),
               ("StockCharts: The DecisionPoint Thrust/Trend Model - Part I", "https://articles.stockcharts.com/article/articles-decisionpoint-2016-03-the-decisionpoint-thrusttrend-model---part-i/")]),
    P("elder-triple-screen", "Elder Triple Screen", "Alexander Elder's Triple Screen (weekly tide, daily wave, breakout trigger)", "trend", ["alexander-elder"], "D", FT.elder_triple,
      "Three screens in a row: the weekly trend must be up, the daily chart must show a pullback, and price must then break the previous day's high. Out when the weekly trend turns down.",
      ["In when, as of yesterday, the weekly MACD histogram (12, 26, 9) was rising and the 2-day average of the Force Index (price change × volume) was below zero, and today's close is above yesterday's high.",
       "Out when the weekly histogram turns down, or on a close below the lower of the entry day's and the previous day's lows (the protective stop)."],
      ["Elder's trigger is a buy-stop order just above the previous day's high, filled during the day. Be The Puck waits for a close above it.",
       "Elder leaves exits to the trader. Selling when the weekly tide turns or the first stop is hit is Be The Puck's reduction.",
       "The weekly screen uses finished weeks only (Friday's close, Sunday's for crypto). Inside a week it reads the week before. A buy is skipped if the week that ends that day turns the histogram down.",
       "Elder also sells short when the weekly tide is down. Be The Puck holds T-bills instead."],
      "Futures magazine (1986); Trading for a Living (1993)",
      sources=[("Incredible Charts: MACD Histogram (Elder's weekly first screen, 12-26-9)", "https://www.incrediblecharts.com/technical/macd_and_histogram.php"),
               ("AskTraders: Elder's Triple Screening Strategy", "https://www.asktraders.com/learn-to-trade/trading-guide/elders-triple-screening-strategy/"),
               ("TakeProfit: Triple Screen Trading System by Alexander Elder", "https://takeprofitapp.com/en/learn/triple-screen-trading-system")],
      warm=1500),
    P("raschke-holy-grail", "Holy Grail", "Raschke and Connors' Holy Grail (ADX pullback to the 20-day EMA)", "trend", ["linda-bradford-raschke", "larry-connors"], "D", FT.holy_grail,
      "In a strong uptrend, buy the first pullback to the 20-day EMA once price takes out the high of the day that touched it. Sell at the old high, or below the pullback low.",
      ["In when, within 5 days of a pullback day, a close tops that day's high while ADX (14) is still above 30. A pullback day has ADX above 30, +DI above −DI, and a low at or below the 20-day EMA.",
       "Out on a close below the pullback day's low (the stop), or at or above the highest high of the 20 days before the pullback (the target)."],
      ["ADX measures trend strength, and +DI above −DI says the trend is up. Descriptions of the setup ask for ADX above 30 with rising prices; reading that as +DI above −DI is Be The Puck's choice.",
       "The 5-day entry window and the 20-day high used as the target are Be The Puck's choices. Neither number is published.",
       "A 20-day exponential average, as most descriptions of Street Smarts use. Some write-ups use a simple one.",
       "Raschke enters on a buy-stop during the day. Be The Puck waits for a close above the pullback day's high; that close may come on a day that also dips to the average. A close already at the target counts as no trade.",
       "Be The Puck sells the whole position at the target."],
      "Street Smarts: High Probability Short-Term Trading Strategies (1995)",
      sources=[("investingLive: Getting to know the Holy Grail strategy", "https://investinglive.com/Education/!/how-to-trade-by-holy-grail-strategy-20210329"),
               ("Trading Setups Review: The Holy Grail Trading Setup", "https://tradingsetupsreview.com/the-holy-grail-trading-setup"),
               ("Capital.com: Holy Grail trading strategy", "https://capital.com/en-gb/learn/trading-strategies/holy-grail-trading-strategy")]),

    # ------------------------------------------------------------ breakouts
    P("four-week-rule", "Four-Week Rule", "Donchian's four-week rule", "breakout", ["richard-donchian"], "D", F.donchian,
      "Buy when price closes above its highest high of the last four weeks; sell when it closes below the lowest low.",
      ["In when a daily close is above the prior 20-day high.", "Out when a daily close is below the prior 20-day low."],
      ["The original is always in the market, long or short, and used calendar weeks. Be The Puck uses 20 trading days and holds T-bills instead of shorting."],
      "Attributed to Richard Donchian (1950s–60s)"),
    P("turtle-system-1", "Turtle System 1", "Turtle System 1 (20/10)", "breakout", ["richard-dennis-william-eckhardt"], "D", F.turtle1,
      "The Turtles' short-term system: buy a 20-day breakout, sell a 10-day low, but skip a breakout if the last one would have been a winner.",
      ["In on a close above the prior 20-day high, unless the previous breakout would have won. Then wait for a 55-day breakout instead.",
       "Out on a close below the prior 10-day low, or 2 N (two average true ranges) below the entry."],
      ["The Turtles also shorted, added up to four units and sized by volatility. Be The Puck tests one long unit."], "The Original Turtle Trading Rules (1983 program, published 2003)"),
    P("turtle-system-2", "Turtle System 2", "Turtle System 2 (55/20)", "breakout", ["richard-dennis-william-eckhardt"], "D", F.turtle2,
      "The Turtles' long-term system: buy every 55-day breakout, sell a 20-day low.",
      ["In on a close above the prior 55-day high.", "Out on a close below the prior 20-day low, or 2 N below the entry."],
      ["No shorts, no adding units, signals on closes."], "The Original Turtle Trading Rules (1983 program, published 2003)"),
    P("clenow-trend-following", "Clenow Trend", "Clenow's core trend-following model", "breakout", ["andreas-clenow"], "D", F.clenow_trend,
      "The model behind Following the Trend: buy a 50-day high when the 50-day EMA is above the 100-day, then ride it with a stop three ATRs below the best close.",
      ["In on a new 50-day closing high while the 50-day EMA is above the 100-day EMA.", "Out when the close falls three average true ranges (20-day) below the highest close since entry."],
      ["Clenow trades about 50 futures markets long and short with volatility sizing. A single stock, long-only, is a big simplification.",
       "The ATR look-back is not in the book's summary; 20 days is Be The Puck's choice."], "Following the Trend (2013)"),
    P("darvas-box", "Darvas Box", "Darvas box breakout", "breakout", ["nicolas-darvas"], "D", F.darvas,
      "A rising stock climbs in a stack of boxes. Buy when it breaks out of the top of a box; sell if it falls out of the bottom.",
      ["A box top is a high that isn't beaten for three days; the bottom is a low that holds for three days after that.",
       "In on a close above the box top. Out on a close below the latest box bottom, which ratchets up as new boxes form."],
      ["The three-day box rule is the usual reading of the book. Darvas also judged volume and picked stocks at new highs."],
      "How I Made $2,000,000 in the Stock Market (1960)"),
    P("keltner-channel-breakout", "Keltner Channel", "Keltner channel breakout", "breakout", ["chester-keltner", "linda-bradford-raschke"], "D", F.keltner,
      "A channel two average true ranges above and below a 20-day EMA. A close above the top says the trend has room to run.",
      ["In on a close above the upper channel (20-day EMA + 2 × 10-day ATR).", "Out on a close below the 20-day EMA."],
      ["Keltner's 1960 version used a 10-day average and the daily range. The ATR version is the modern default.",
       "Exiting at the middle line is a common modern choice, not Keltner's."], "How to Make Money in Commodities (1960); modern ATR version"),
    P("bollinger-breakout", "Bollinger Breakout", "Bollinger band breakout", "breakout", ["john-bollinger"], "D", F.bb_break,
      "Bollinger says closes outside the bands usually mean the move continues. Buy a close above the upper band; sell when price slips under the middle.",
      ["In on a close above the upper band (20-day average + 2 standard deviations).", "Out on a close below the 20-day average."],
      ["Bollinger's own breakout method starts from a 'squeeze', and he says the middle band isn't meant as a crossover line. The exit is Be The Puck's choice."],
      "Bollinger on Bollinger Bands (2001)"),
    P("chandelier-exit", "Chandelier Exit", "Chandelier exit trend ride", "breakout", ["chuck-lebeau"], "D", F.chandelier,
      "LeBeau's stop hangs three average true ranges below the highest high, like a chandelier from the ceiling. Paired here with a 22-day breakout entry.",
      ["In on a close above the prior 22-day closing high.", "Out on a close below the chandelier stop (22-day high − 3 × 22-day ATR)."],
      ["The Chandelier Exit is only an exit. The breakout entry is Be The Puck's pairing."], "Computer Analysis of the Futures Markets (1992); popularised by Elder (2002)"),

    P("wilder-volatility-system", "Wilder Volatility System", "J. Welles Wilder's Volatility System", "breakout", ["j-welles-wilder"], "D", FT.wilder_vol,
      "Wilder's stop-and-reverse system from the book that introduced average true range. Stay long until the close drops 3 average true ranges below the best close of the trade, then wait in cash until the close rises 3 ranges above the lowest close since.",
      ["Out when a close falls more than 3 × the 7-day average true range (a typical day's range) below the highest close since going in.",
       "In when a close rises more than 3 × the 7-day average true range above the lowest close since going out."],
      ["Wilder's system is always in the market, long or short. Be The Puck holds T-bills instead of shorting.",
       "Wilder's multiplier runs from 2.8 to 3.1; 3.0 is the standard value.",
       "The 7-day ATR uses Wilder's smoothing and the previous day's value, as in eSignal's version of the book.",
       "The test starts out of the market, measuring from the first close."],
      "New Concepts in Technical Trading Systems (1978)",
      sources=[("eSignal: Wilder's Volatility study", "https://download.esignal.com/products/workstation/help/charts/studies/wilders_volatility.htm"),
               ("MotiveWave: Volatility Index (Wilder, New Concepts)", "https://docs.motivewave.com/studies/u-v"),
               ("Oxford Capital Strategies: Wilder Volatility System", "https://oxfordstrat.com/?p=10080")]),
    P("pf-double-top-breakout", "P&F Double Top", "Point & figure double-top breakout (3-box reversal)", "breakout", ["a-w-cohen", "thomas-dorsey"], "D", FT.pf_double_top,
      "A point & figure chart ignores time and plots only moves of a set size, in columns of X's (rising) and O's (falling). Own the stock after an X column tops the one before it; sell after an O column breaks below the one before it.",
      ["In on a double-top breakout: the current X column rises at least one box above the top of the previous X column.",
       "Out on a double-bottom breakdown: the current O column falls at least one box below the bottom of the previous O column.",
       "Otherwise the rule keeps the chart's last signal."],
      ["Boxes are 2% apart, and a new column needs a 3-box reversal (about 6%). Dorsey's classic box table uses fixed price bands; ChartSchool's examples use 1% boxes.",
       "The chart is built from daily highs and lows by StockCharts' high-low method: a new box from the high wins, and the low only counts if it reverses the column.",
       "The signal fires on the day the breakout box fills during the day. Be The Puck acts on that day's close."],
      "How to Use the Three-Point Reversal Method of Point & Figure Stock Market Trading (1947); Point & Figure Charting (1995)",
      sources=[("StockCharts ChartSchool: P&F Bullish Breakouts", "https://chartschool.stockcharts.com/table-of-contents/chart-analysis/point-and-figure-charts/classic-patterns/p-and-f-bullish-breakouts"),
               ("StockCharts ChartSchool: P&F Scaling and Timeframes (box size, high-low method)", "https://chartschool.stockcharts.com/table-of-contents/chart-analysis/point-and-figure-charts/point-and-figure-basics/point-and-figure-scaling-and-timeframes"),
               ("StockCharts ChartSchool: Introduction to Point & Figure Charts", "https://chartschool.stockcharts.com/table-of-contents/chart-analysis/point-and-figure-charts/point-and-figure-basics/introduction-to-point-and-figure-charts")],
      warm=1500),
    P("chande-kroll-stop", "Chande Kroll Stop", "Chande Kroll Stop (10, 3, 20)", "breakout", ["tushar-chande", "stanley-kroll"], "D", FT.chande_kroll,
      "Two stop lines built from recent highs, lows and average ranges. Be in once the close clears both lines; get out when it falls below the long stop.",
      ["The long stop is the highest value over 20 days of the 10-day high minus 3 × the 10-day average true range. The short stop is the lowest value over 20 days of the 10-day low plus 3 × that range.",
       "In when a close is above both stop lines.",
       "Out when a close is below the long stop. Between the lines, the rule keeps its last call."],
      ["The book's settings (10, 3, 20) with a simple-average ATR, per the pandas-ta notes that cite the book (p. 95). TradingView's popular default (10, 1, 9 with Wilder's ATR) is a different variant.",
       "The stops serve long and short trades. Be The Puck only takes the long side and acts on daily closes."],
      "The New Technical Trader (1994)",
      sources=[("pandas-ta-classic: Chande Kroll Stop source and docstring (book vs TradingView defaults)", "https://raw.githubusercontent.com/xgboosted/pandas-ta-classic/main/pandas_ta_classic/trend/cksp.py"),
               ("Deltavalue: Chande Kroll Stop Indikator", "https://www.deltavalue.de/?p=48945")]),
    P("headley-acceleration-bands", "Acceleration Bands", "Price Headley's Acceleration Bands breakout", "breakout", ["price-headley"], "D", FT.accel_bands,
      "Bands that widen with each day's range. Headley says two closes in a row above the upper band mark a stock that is accelerating, and the first close back inside says the run is probably over.",
      ["In after two closes in a row above the upper band (the 20-day average of high × (1 + 4 × (high − low) ÷ (high + low))).",
       "Out on the first close back below the upper band."],
      ["The band formula (factor 4, 20 days) comes from TC2000's and LuxAlgo's documentation. Headley's own article gives the 20-day setting and the trading rules but not the formula.",
       "Headley uses the bands on daily, weekly and monthly charts. Be The Puck tests daily bars."],
      "BigTrends; Indicator in Focus: Acceleration Bands, MoneyShow (2015)",
      sources=[("MoneyShow: Indicator in Focus: Acceleration Bands (Price Headley)", "https://moneyshow.com/articles/daytraders-28080"),
               ("TC2000 Help: Acceleration Bands (formula)", "https://help.tc2000.com/m/69445/l/755840-acceleration-bands"),
               ("LuxAlgo Library: Acceleration Bands", "https://www.luxalgo.com/library/concept/acceleration-bands.md")]),
    P("ttm-squeeze", "TTM Squeeze", "John Carter's TTM Squeeze", "breakout", ["john-carter"], "D", FT.ttm_squeeze,
      "When the Bollinger Bands shrink inside the Keltner Channel, the market is coiled. Buy when that squeeze releases with momentum positive and rising; sell when momentum fades for two days.",
      ["The squeeze is on while the Bollinger Bands (20 days, 2 standard deviations) sit inside the Keltner Channel (20 days, 1.5 × average true range). It fires on the first day it turns off.",
       "In on the firing day if the momentum histogram is above zero and rising.",
       "Out after two days in a row of falling momentum, or when momentum drops below zero."],
      ["Carter's momentum formula is proprietary. Be The Puck uses StockCharts' version: a 20-day linear-regression reading of the close minus the average of the 20-day midrange and the 20-day average.",
       "The Keltner Channel is built as a 20-day average ± 1.5 × the 20-day simple average of true range.",
       "A squeeze that fires with negative or falling momentum is Carter's short signal, so the rule stays out."],
      "Mastering the Trade (2005), chapter 11",
      sources=[("StockCharts ChartSchool: TTM Squeeze", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/ttm-squeeze"),
               ("Simpler Trading: Mastering the Trade - The Squeeze", "https://www.simplertrading.com/squeeze")]),
    P("crabel-nr7", "NR7 Breakout", "Toby Crabel's NR7 breakout (daily)", "breakout", ["toby-crabel"], "D", FT.crabel_nr7,
      "An NR7 day has the narrowest high-to-low range of the last seven. Quiet days tend to come before big moves, so buy a close above that day's high and sell a close below its low.",
      ["An NR7 day's range is smaller than each of the 6 days before it.",
       "In when a later close is above the high of the latest NR7 day.",
       "Out when a later close is below the low of the latest NR7 day. Each new NR7 day resets both levels."],
      ["Crabel traded breakouts from the day's opening range and took profits fast. Be The Puck uses StockCharts' daily version and holds until the opposite break.",
       "Breakouts are judged on closes, not intraday highs and lows.",
       "The range is measured in price (high minus low), as Crabel did, not in percent."],
      "Day Trading With Short Term Price Patterns and Opening Range Breakout (1990)",
      sources=[("StockCharts ChartSchool: Narrow Range Day NR7", "https://chartschool.stockcharts.com/table-of-contents/trading-strategies-and-models/trading-strategies/narrow-range-day-nr7")]),
    P("bollinger-squeeze", "Bollinger Squeeze", "Bollinger Method I: the squeeze breakout", "breakout", ["john-bollinger"], "D", FT.bb_squeeze,
      "Bollinger's own volatility breakout. Wait for the bands to pinch to their narrowest in about 6 months, then buy the first close above the upper band.",
      ["A squeeze is BandWidth (the gap between the bands divided by the middle band) at its lowest of the last 125 days.",
       "In on a close above the upper band (20-day average + 2 standard deviations) when a squeeze happened in the last 5 days.",
       "Out on a close below the 20-day average."],
      ["Bollinger's Method I gives the entry, not the exit. Selling below the middle band matches the site's Bollinger Breakout, so the two can be compared.",
       "Bollinger also reads volume indicators to guess which way the breakout will go. They are not used here.",
       "This is the squeeze-filtered form of the Bollinger Breakout play. John Carter's TTM Squeeze is a cousin that compares the bands with a Keltner Channel instead."],
      "Bollinger on Bollinger Bands (2001); Bollinger Bands Method I manual (2021)",
      sources=[("Bollinger Bands Method I manual (bollingerbands.com, PDF)", "https://www.bollingerbands.com/_files/ugd/58be43_f5e967053af44fa083340cacfc5e6226.pdf"),
               ("StockCharts ChartSchool: Bollinger Band Squeeze", "https://chartschool.stockcharts.com/table-of-contents/trading-strategies-and-models/trading-strategies/bollinger-band-squeeze")]),

    # ------------------------------------------------------------ momentum
    P("time-series-momentum", "12-Month Momentum", "Time-series momentum (12-month)", "momentum", ["moskowitz-ooi-pedersen"], "M", F.tsmom,
      "Hold the asset while its return over the last 12 months beats Treasury bills. Otherwise sit in bills.",
      ["In when the 12-month return at month-end beats the 12-month T-bill return.", "Out, in T-bills, when it doesn't."],
      ["The paper also goes short. Be The Puck tests the long-only version an individual investor can run."], "Journal of Financial Economics (2012)"),
    P("twelve-one-momentum", "12-1 Momentum", "12-1 momentum (single stock)", "momentum", ["jegadeesh-titman"], "M", F.mom_12_1,
      "The classic momentum measure: the return from a year ago to a month ago. Hold the stock while it is positive.",
      ["In at month-end when the return from 12 months ago to 1 month ago is above zero.", "Out when it is zero or below."],
      ["Jegadeesh and Titman ranked thousands of stocks and bought the winners. Testing one stock against zero is time-series momentum, a related idea.",
       "The skip-a-month form came later; their 1993 paper skipped at most a week."], "Journal of Finance (1993)"),
    P("dual-momentum", "Dual Momentum", "Dual momentum (stock vs SPY vs T-bills)", "momentum", ["gary-antonacci"], "M", F.dual_mom,
      "Antonacci's two tests at once: the stock must beat T-bills (absolute momentum) and beat the market (relative momentum) over 12 months.",
      ["In at month-end when the stock's 12-month return beats both T-bills and SPY.", "Out otherwise."],
      ["Antonacci applies dual momentum to whole asset classes, not single stocks, and holds bonds when out.",
       "On SPY itself only the T-bill test applies."], "Dual Momentum Investing (2014)", relative=True),
    P("stocks-on-the-move", "Stocks on the Move", "Clenow's Stocks on the Move momentum", "momentum", ["andreas-clenow"], "D", F.stocks_on_move,
      "Clenow scores momentum as the steepness of a 90-day trend line times how straight it is. Buy only when the market is above its 200-day.",
      ["In when the momentum score is positive, the stock is above its 100-day average, it hasn't moved 15% in a day in the last 90 days, and SPY is above its 200-day.",
       "Out when the score turns negative, the stock drops below its 100-day, or a 15% gap appears."],
      ["The real strategy ranks the S&P 500, buys the top fifth and rebalances weekly. 'Score above zero' is a much looser stand-in.",
       "Checked daily here rather than every Wednesday."], "Stocks on the Move (2015)", relative=True),
    P("52-week-high", "52-Week High", "52-week-high momentum", "momentum", ["george-hwang"], "M", F.high52,
      "Stocks trading near their 52-week high tend to keep going, because traders anchor on the old high. Hold while it is close.",
      ["In at month-end when the close is within 5% of its 52-week closing high.", "Out when it slips more than 15% below the high."],
      ["The paper ranks all stocks against each other. The 95% and 85% thresholds are Be The Puck's choice."], "Journal of Finance (2004)"),
    P("levy-relative-strength", "Levy Relative Strength", "Levy 27-week relative strength", "momentum", ["robert-levy"], "W", F.levy,
      "One of the first academic momentum tests: own stocks trading well above their 27-week average, and stronger than the market on the same measure.",
      ["In when the weekly close is above its 27-week average and that ratio beats SPY's.", "Out when either fails."],
      ["Levy ranked a universe of stocks. Comparing with SPY stands in for the ranking."], "Journal of Finance (1967)", relative=True),
    P("macd-signal-cross", "MACD Signal Cross", "MACD signal-line crossover", "momentum", ["gerald-appel"], "D", F.macd_signal,
      "The most common MACD signal: bullish when the MACD line crosses above its 9-day signal line.",
      ["In when MACD (12, 26) is above its 9-day signal line.", "Out when it is below."],
      ["Appel also reads divergences and the zero line, which this rule ignores."], "Gerald Appel, late 1970s"),
    P("elder-impulse", "Elder Impulse", "Elder impulse system", "momentum", ["alexander-elder"], "D", F.elder_impulse,
      "Colours each day by trend (13-day EMA) and momentum (MACD histogram). Green when both rise, red when both fall.",
      ["In on a green day: the 13-day EMA and the MACD histogram both rising.", "Out on a red day: both falling. Mixed days keep the last call."],
      ["Elder uses the colours as a filter inside his Triple Screen, not as a stand-alone system."], "Come Into My Trading Room (2002)"),
    P("know-sure-thing", "Know Sure Thing", "Pring's Know Sure Thing (KST)", "momentum", ["martin-pring"], "D", F.kst,
      "Four smoothed rates of change, weighted and added together. When the KST crosses above its signal line, momentum is turning up.",
      ["In when the KST is above its 9-day signal line.", "Out when it is below."],
      ["Pring preferred weekly and monthly KST for the main trend. The daily version is a shorter-term reading."],
      "Technical Analysis of Stocks & Commodities, September 1992"),
    P("coppock-curve", "Coppock Curve", "Coppock curve", "momentum", ["edwin-coppock"], "M", F.coppock,
      "A monthly momentum line built to spot the end of bear markets. The buy signal is the curve turning up from below zero.",
      ["In at month-end when the curve, below zero, turns up.", "Out when it is below zero and falling."],
      ["Coppock only defined the buy. The exit is Be The Puck's addition.", "He designed it for broad indexes, not single stocks."],
      "Barron's (1962, some sources say 1965)"),
    P("cci-100", "CCI +100", "Lambert's CCI breakout", "momentum", ["donald-lambert"], "D", F.cci100,
      "The Commodity Channel Index measures how far price has run from its average. Lambert bought above +100 and sold when it fell back.",
      ["In when the CCI (20) crosses above +100.", "Out when it crosses back below +100."],
      ["The original also sells short below −100."], "Commodities magazine (1980)"),

    P("trix-signal-cross", "TRIX Signal Cross", "Hutson TRIX (15) signal-line crossover", "momentum", ["jack-hutson"], "D", FM.trix_cross,
      "TRIX is the daily percent change of a 15-day average smoothed three times over, which filters out most day-to-day noise. Hold while it is above its 9-day signal line.",
      ["TRIX is the 1-day percent change of the close after it has been through a 15-day exponential average three times in a row. The signal line is a 9-day exponential average of TRIX.",
       "In when TRIX crosses above its signal line.", "Out when it crosses below."],
      ["Hutson's 1983 version smoothed the log of price, set the length from the market's own cycle (his examples used 8 and 17 days) and sold on a fixed reversal in TRIX. The 15-day setting and the signal-line cross are the StockCharts standard used here.",
       "StockCharts also lists a slower signal, TRIX crossing zero, which is not tested here."],
      "'Good Trix', Technical Analysis of Stocks & Commodities (1983)",
      sources=[("StockCharts ChartSchool: TRIX", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/trix"),
               ("Hutson: Good Trix, Stocks & Commodities V.1:5 (1983)", "https://c.mql5.com/forextsd/forum/64/trix_jack_huton.pdf")]),
    P("tsi-zero-line", "TSI Zero Line", "Blau True Strength Index (25, 13) zero line", "momentum", ["william-blau"], "D", FM.tsi_zero,
      "Blau's True Strength Index smooths daily price changes twice and divides by the smoothed size of those changes. Hold while it is above zero.",
      ["TSI = 100 × the 13-day EMA of the 25-day EMA of daily price changes, divided by the same double average of their size. It runs from −100 to +100.",
       "In when TSI crosses above zero.", "Out when it crosses below zero."],
      ["Blau also used signal-line crosses and divergences. StockCharts calls the zero-line cross the purest signal, and it is the one tested here.",
       "25 and 13 days are Blau's default smoothing lengths."],
      "'True Strength Index', Stocks & Commodities (November 1991)",
      sources=[("StockCharts ChartSchool: True Strength Index", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/true-strength-index"),
               ("Wikipedia: True strength index", "https://en.wikipedia.org/wiki/True_strength_index")]),
    P("keller-13612w", "13612W Momentum", "Keller & Keuning 13612W momentum filter", "momentum", ["keller-keuning"], "M", FM.keller_13612w,
      "A fast momentum score that blends the 1, 3, 6 and 12-month returns and leans hardest on the most recent. Hold while the score is above zero.",
      ["At each month-end, the score is 12 × the 1-month return + 4 × the 3-month return + 2 × the 6-month return + the 12-month return. Divided by 4, it is the average of the four returns, each scaled to a yearly pace.",
       "In when the score is above zero.", "Out when it is zero or below."],
      ["Keller and Keuning use the score inside their VAA and DAA strategies, which pick among asset-class ETFs and move to bonds or cash when too many look weak. On one stock, the stock is the only risky asset and cash is the safe one.",
       "Signals are acted on the first trading day of the next month."],
      "'Breadth Momentum and Vigilant Asset Allocation (VAA)', SSRN (2017)",
      sources=[("CXO Advisory: VAA summary (2017)", "https://www.cxoadvisory.com/technical-trading/conservative-breadth-rule-for-asset-class-momentum-crash-protection/"),
               ("Trading Terminal: VAA explainer with the 13612W formula", "https://tradingterminal.com/opinion/this-momentum-based-strategy-aims-to-boost-your-returns-and-lower-your-risk"),
               ("R-bloggers: KDA asset allocation (13612W momentum)", "https://www.r-bloggers.com/2019/01/right-now-its-kdaasset-allocation/")]),
    P("market-state-momentum", "Market-State Momentum", "12-1 momentum only after up markets", "momentum", ["cooper-gutierrez-hameed"], "M", FM.market_state_mom,
      "Momentum has paid after the market has risen and failed after it has fallen. Hold a stock with positive 12-1 momentum only while SPY is up over the last 3 years.",
      ["In at month-end when the stock's return from 12 months ago to 1 month ago is above zero and SPY's return over the last 36 months is above zero.",
       "Out at month-end when either is zero or below."],
      ["The paper reported when momentum paid, not a trading rule. Turning it into a hold-or-cash switch is Be The Puck's.",
       "The paper sorts NYSE and AMEX stocks into winner and loser portfolios. A positive 12-1 return stands in for being a winner, as in Be The Puck's 12-1 play.",
       "The paper calls the market up when the value-weighted market's past 36-month return is positive. SPY's 36-month return stands in. On SPY itself, both tests use SPY.",
       "Signals are acted on the first trading day of the next month."],
      "'Market States and Momentum', Journal of Finance (2004)", relative=True,
      sources=[("SUFE academic newsletter: Market States and Momentum (abstract)", "https://academicnewsletter.sufe.edu.cn/info/361185"),
               ("Waikato thesis restating the market-state definition", "https://researchcommons.waikato.ac.nz/bitstreams/20849f32-e124-4a23-8d14-832cbc4b28a8/download")]),
    P("frog-in-the-pan", "Frog in the Pan", "Frog-in-the-pan momentum (12-1 with steady gains)", "momentum", ["da-gurun-warachka"], "D", FM.frog_pan,
      "Momentum built from many small up days lasts longer than momentum from a few big jumps, because investors underreact to slow, steady news. Hold a 12-1 winner only if more of its days were up than down.",
      ["Checked on the last trading day of each month, over the window from 12 months ago to 1 month ago.",
       "In when the return over that window is above zero and the window had more up days than down days.",
       "Out at month-end when either fails."],
      ["The paper sorts all stocks by past return, then by how steadily the return came (its 'information discreteness' score). Holding a stock with a positive return and more up days than down days is Be The Puck's single-stock cut-off.",
       "Signals are acted on the first trading day of the next month. Days with no change count as neither up nor down.",
       "The window ends a month before each check, so each month-end's call is already set a month ahead. No price on the day can change it."],
      "'Frog in the Pan: Continuous Information and Momentum', Review of Financial Studies (2014)", warm=600,
      sources=[("Da, Gurun & Warachka: Frog in the Pan (paper)", "https://academicweb.nd.edu/~zda/Frog.pdf")]),
    P("pmo-signal-cross", "PMO Signal Cross", "DecisionPoint Price Momentum Oscillator crossover", "momentum", ["carl-swenlin"], "D", FM.pmo_cross,
      "Swenlin's Price Momentum Oscillator smooths the daily percent change twice. Hold while it is above its 10-day signal line.",
      ["The PMO is a 20-day smoothing of 10 × a 35-day smoothing of the 1-day percent change. Each smoothing is an exponential average that weights the newest day by 2/n instead of the usual 2/(n+1).",
       "In when the PMO crosses above its 10-day EMA signal line.", "Out when it crosses below."],
      ["StockCharts warns that PMO crossovers can whipsaw a lot and are best used as alerts, not as a mechanical system.",
       "How the smoothing is started is not documented. Here it starts from the first value."],
      "DecisionPoint (Carl Swenlin), date unverified; documented by StockCharts ChartSchool",
      sources=[("StockCharts ChartSchool: DecisionPoint Price Momentum Oscillator (PMO)", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/decisionpoint-price-momentum-oscillator-pmo")]),

    # ------------------------------------------------------------ mean reversion
    P("rsi-30-70", "RSI 30/70", "RSI 30/70 crossover", "reversion", ["j-welles-wilder"], "D", F.rsi_30_70,
      "The textbook use of Wilder's RSI: buy when it climbs back above 30 (oversold), sell when it drops back below 70 (overbought).",
      ["In when the 14-day RSI crosses up through 30.", "Out when it crosses down through 70."],
      ["Wilder treated failure swings and divergences as stronger signals. The 30/70 cross is a popular simplification.",
       "There is no stop: the rule can hold through a long decline."], "New Concepts in Technical Trading Systems (1978)"),
    P("rsi-2-pullback", "RSI(2) Pullback", "Connors RSI(2) pullback", "reversion", ["larry-connors", "cesar-alvarez"], "D", F.rsi2,
      "Buy a sharp short-term dip, but only in a long-term uptrend, and sell the first bounce.",
      ["In when the stock is above its 200-day average and the 2-day RSI is below 10.", "Out on a close above the 5-day average."],
      ["Connors buys on the signal day's close, as Be The Puck does. No stop-loss, as in the book."], "Short Term Trading Strategies That Work (2008)"),
    P("double-7s", "Double 7s", "Connors & Alvarez Double 7s", "reversion", ["larry-connors", "cesar-alvarez"], "D", F.double7,
      "Above the 200-day average, buy a close at a 7-day low and sell a close at a 7-day high.",
      ["In when the stock is above its 200-day average and closes at its lowest close of the last 7 days.", "Out when it closes at its highest close of the last 7 days."],
      ["Tested by the authors on ETFs. Single stocks are an extension."], "Short Term Trading Strategies That Work (2008)"),
    P("bollinger-reversion", "Bollinger Reversion", "Bollinger band reversion", "reversion", ["john-bollinger"], "D", F.bb_revert,
      "A common way traders use the bands, not Bollinger's own: buy a close below the lower band, sell when price gets back to the middle.",
      ["In on a close below the lower band (20-day average − 2 standard deviations).", "Out on a close above the 20-day average."],
      ["This runs against Bollinger's advice that tags of the bands are not signals. It is shown because so many traders use it."],
      "Trader practice using Bollinger Bands"),
    P("stochastic-20-80", "Stochastic 20/80", "Stochastic 20/80 crossover", "reversion", ["george-lane"], "D", F.stochastic,
      "Where today's close sits in the last 14 days' range. Buy a %K/%D cross up in the oversold zone, sell a cross down in the overbought zone.",
      ["In when %K crosses above %D while %D is below 20.", "Out when %K crosses below %D while %D is above 80."],
      ["Lane said divergence was the only signal that matters. The zone cross is the textbook simplification."], "Lane's Stochastics, Stocks & Commodities (1984)"),
    P("williams-percent-r", "Williams %R", "Williams %R −80/−20", "reversion", ["larry-williams"], "D", F.willr,
      "The stochastic turned upside down: 0 is the top of the 14-day range, −100 the bottom. Buy out of oversold, sell out of overbought.",
      ["In when %R crosses up through −80.", "Out when it crosses down through −20."],
      ["Williams read %R differently in bull, bear and sideways markets. This is the modern charting convention."],
      "How I Made One Million Dollars Last Year Trading Commodities (1973)"),
    P("demark-setup-9", "DeMark 9-Count", "DeMark 9-count setup", "reversion", ["tom-demark"], "D", F.demark9,
      "Count closes below the close four days earlier. Nine in a row marks a selling streak that is likely spent.",
      ["In when a buy setup completes: 9 straight closes below the close 4 days earlier.", "Out when a sell setup completes: 9 straight closes above it."],
      ["DeMark's full Sequential waits for a 13-bar countdown and other qualifiers. The bare 9-count is a popular shortcut.",
       "TD Sequential is a trademark of DeMark Analytics."], "The New Science of Technical Analysis (1994)"),
    P("mayer-multiple", "Mayer Multiple", "Mayer Multiple below 2.4", "reversion", ["trace-mayer"], "D", F.mayer,
      "Price divided by its 200-day average. Mayer found buying bitcoin below 2.4 worked best; above that was bubble territory.",
      ["In while the close is less than 2.4 times its 200-day average.", "Out when it reaches 2.4 or more."],
      ["Mayer used it to decide when to keep buying, not when to sell. Selling above 2.4 is Be The Puck's reading.",
       "On ordinary stocks a price 2.4 times the 200-day is rare, so this is close to buy and hold."], "Bitcoin Knowledge (around 2017)"),

    P("connorsrsi-pullback", "ConnorsRSI Pullback", "ConnorsRSI (3, 2, 100) pullback strategy", "reversion", ["larry-connors", "cesar-alvarez", "matt-radtke"], "D", FM.connorsrsi_pullback,
      "Buy a stock in a strong trend after a sharp one-day sell-off pushes ConnorsRSI below 10, and sell when it recovers above 70.",
      ["ConnorsRSI averages three 0 to 100 readings: a 3-day RSI of the close, a 2-day RSI of the current up or down streak, and where today's 1-day return ranks among the previous 100.",
       "In at the close when the 10-day ADX (a gauge of trend strength) is above 30, the day's low is at least 4% below the prior close, the close is in the bottom 25% of the day's range, and ConnorsRSI is below 10.",
       "Out at the close when ConnorsRSI is above 70."],
      ["The guidebook buys the next day with a limit order 2% to 10% below the signal close. Be The Puck buys at the signal close, a worse price than the book's.",
       "The guidebook tests a range of settings. Its worked example uses a 4% drop, the bottom 25% of the range, ConnorsRSI below 10 and an exit above 70, and those are used here.",
       "The $5 minimum price and 250,000-share average volume filters are dropped. As in the guidebook, there is no 200-day average filter.",
       "Days where the high equals the low give no entry."],
      "An Introduction to ConnorsRSI, Connors Research guidebook (2012)",
      sources=[("An Introduction to ConnorsRSI (Connors, Alvarez & Radtke, 2012)", "https://c.mql5.com/forextsd/forum/119/connorsrsi-pullbacks-guidebook.pdf"),
               ("StockCharts ChartSchool: ConnorsRSI", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/connorsrsi")]),
    P("laguerre-rsi", "Laguerre RSI", "Ehlers Laguerre RSI 0.2/0.8", "reversion", ["john-ehlers"], "D", FM.laguerre_rsi,
      "Ehlers' fast RSI, built from four stages of a Laguerre filter instead of a fixed look-back, so it reacts with little lag. Buy when it climbs back above 0.2, sell when it drops back below 0.8.",
      ["The Laguerre RSI runs from 0 to 1, with a damping factor (gamma) of 0.5.",
       "In when it crosses up through 0.2.", "Out when it crosses down through 0.8."],
      ["Gamma 0.5 is the value in Ehlers' published code. He says traders can adjust it.",
       "The filter starts from the first close.",
       "There is no stop: the rule can hold through a long decline."],
      "'Time Warp - Without Space Travel' (MESA Software); Cybernetic Analysis for Stocks and Futures (2004)",
      sources=[("Ehlers: Time Warp - Without Space Travel", "https://mesasoftware.com/papers/TimeWarp.pdf"),
               ("Wiley: Cybernetic Analysis for Stocks and Futures, contents", "https://gov.wiley.com/WileyCDA/WileyTitle/productCd-0471463078,descCd-tableOfContents.html")]),
    P("stochrsi-20-80", "StochRSI 20/80", "Chande & Kroll StochRSI 0.2/0.8", "reversion", ["tushar-chande", "stanley-kroll"], "D", FM.stochrsi,
      "The stochastic formula applied to the 14-day RSI: where today's RSI sits in its own 14-day range. It reaches overbought and oversold far more often than RSI does. Buy out of oversold, sell out of overbought.",
      ["StochRSI = (RSI − lowest RSI of the last 14 days) ÷ (highest − lowest), from 0 to 1.",
       "In when StochRSI crosses up through 0.2.", "Out when it crosses down through 0.8."],
      ["Chande and Kroll defined 0.8 and 0.2 as overbought and oversold levels, not trading rules. Buying the cross back up through 0.2 and selling the cross down through 0.8 mirrors Be The Puck's RSI 30/70 play.",
       "Raw StochRSI is used. Many platforms smooth it with a 3-day average.",
       "There is no stop: the rule can hold through a long decline."],
      "The New Technical Trader (1994)",
      sources=[("StockCharts ChartSchool: StochRSI", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/stochrsi")]),
    P("ibs-reversion", "IBS Reversion", "Internal bar strength below 0.2", "reversion", ["alexander-pagonidis"], "D", FM.ibs,
      "Internal bar strength is where the close lands in the day's range. A close near the low has tended to bounce the next day, so buy those closes and hold for one day.",
      ["IBS = (close − low) ÷ (high − low). 0 means it closed at the low, 1 at the high.",
       "In at the close when IBS is below 0.2.", "Out at the next close unless IBS is below 0.2 again."],
      ["The documented effect is about the next day's return, so the hold is one day. A common variant holds until IBS closes above 0.8.",
       "Pagonidis studied equity ETFs. Single stocks are an extension.",
       "Days where the high equals the low give no signal."],
      "'The IBS Effect: Mean Reversion in Equity ETFs', NAAIM Founders Award entry (2014)",
      sources=[("arXiv 2306.12434: Internal Bar Strength for trading country ETFs", "https://arxiv.org/pdf/2306.12434"),
               ("NAAIM: Founders Award paper list 2009-2018", "https://www.naaim.org/wp-content/uploads/2018/05/ALL-founders-award-paper-list_2009-2018_web.pdf")]),
    P("connors-percent-b", "Connors %b", "Connors %b three-day oversold", "reversion", ["larry-connors", "cesar-alvarez"], "D", FM.connors_pctb,
      "In a long-term uptrend, buy after the close has sat near or below the bottom of its Bollinger Bands for three days running, and sell once it gets near the top.",
      ["%b shows where the close sits in its Bollinger Bands: 0 at the lower band, 1 at the upper.",
       "In at the close when the stock is above its 200-day average and %b has closed below 0.2 on each of the last 3 days.",
       "Out at the close when %b is above 0.8."],
      ["None of the sources seen give the band settings. Bollinger's standard 20-day bands at 2 standard deviations are assumed.",
       "Connors' aggressive version adds a second unit on a lower close. Be The Puck holds one unit.",
       "Tested by the authors on ETFs. Single stocks are an extension."],
      "High Probability ETF Trading (2009)", flag="Band settings unconfirmed",
      sources=[("Quantified Strategies: Larry Connors %b strategy", "https://quantifiedstrategies.substack.com/p/larry-connors-b-strategy-bollinger-ab6"),
               ("TradingView: Larry Connors %b Strategy (EdgeTools)", "https://jp.tradingview.com/script/yXkWPSlU"),
               ("StockCharts ChartSchool: %B Indicator", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/b-indicator")]),
    P("fisher-transform", "Fisher Transform", "Ehlers Fisher transform trigger cross", "reversion", ["john-ehlers"], "D", FM.fisher,
      "Ehlers stretches price's place in its 10-day range so that turning points stand out sharply. Hold while the Fisher line is above its own value a day earlier.",
      ["Take the midpoint of each day's high and low, place it in its 10-day range on a −1 to +1 scale, smooth it, and apply the Fisher transform, which stretches values near the edges.",
       "In when the Fisher line crosses above its trigger, which is yesterday's Fisher value.",
       "Out when it crosses below."],
      ["Ehlers plots the line and its one-day-old copy as a crossover system for turning points but gives no formal entry or exit. Buying the up-cross and selling the down-cross is Be The Puck's reading.",
       "As in his code, the scaled value is capped at ±0.999 and the smoothing starts from zero."],
      "'Using the Fisher Transform', Stocks & Commodities (November 2002)",
      sources=[("Ehlers: Using The Fisher Transform, Stocks & Commodities V.20:11", "https://c.mql5.com/3/133/Using_The_Fisher_Transform.pdf"),
               ("Wiley: Cybernetic Analysis for Stocks and Futures, contents", "https://gov.wiley.com/WileyCDA/WileyTitle/productCd-0471463078,descCd-tableOfContents.html")]),
    P("short-term-reversal", "1-Month Reversal", "Short-term reversal (last month's laggard)", "reversion", ["jegadeesh-lehmann"], "M", FM.st_reversal,
      "Last month's laggards tend to bounce the next month. Hold the stock for the month after one in which it trailed SPY.",
      ["In at month-end when the stock's return for the month just ended is below SPY's.",
       "Out at month-end when it matched or beat SPY."],
      ["Jegadeesh ranked all stocks by last month's return. Trailing SPY stands in for being one of the losers.",
       "On SPY itself, a down month stands in for trailing the market.",
       "Lehmann's version uses weekly returns. Only the monthly one is tested here.",
       "Returns include dividends, as everywhere on Be The Puck. A price-only index, such as the S&P 500 index itself, trails SPY in most months for that reason alone.",
       "Signals are acted on the first trading day of the next month."],
      "Jegadeesh, Journal of Finance (1990); Lehmann, Quarterly Journal of Economics (1990)", relative=True,
      sources=[("Alpha Architect: Short-term return reversal", "https://alphaarchitect.com/quantitative-momentum-research-short-term-return-reversal/"),
               ("RePEc/IDEAS: Journal of Finance 45(3) 881-98 (1990)", "https://ideas.repec.org/r/bla/jfinan/v45y1990i3p881-98.html"),
               ("NBER Working Paper 2533 (Lehmann)", "https://www.nber.org/papers/w2533.pdf")]),

    # ------------------------------------------------------------ volume
    P("on-balance-volume", "On-Balance Volume", "Granville's on-balance volume trend", "volume", ["joseph-granville"], "D", F.obv,
      "A running total of volume: add it on up days, subtract it on down days. Rising OBV says buyers are accumulating.",
      ["In when OBV is above its 20-day average.", "Out when it is below."],
      ["The OBV is Granville's; the 20-day signal line is Be The Puck's. He read OBV's trend and divergences by eye."],
      "Granville's New Key to Stock Market Profits (1963)"),
    P("chaikin-money-flow", "Chaikin Money Flow", "Chaikin money flow", "volume", ["marc-chaikin"], "D", F.cmf,
      "Weighs each day's volume by where the close lands in the day's range. Positive means buying pressure.",
      ["In when the 21-day CMF rises above +0.05.", "Out when it falls below −0.05. In between, the rule keeps its last call."],
      ["The ±0.05 buffer is StockCharts' suggested filter against whipsaws."], "Marc Chaikin (date unverified)"),
    P("money-flow-index", "Money Flow Index", "Money Flow Index 20/80", "volume", ["quong-soudack"], "D", F.mfi,
      "RSI with volume added. Buy when it climbs out of oversold (20), sell when it drops out of overbought (80).",
      ["In when the 14-day MFI crosses up through 20.", "Out when it crosses down through 80."],
      ["The creators also stress divergences, which this rule ignores."], "Technical Analysis of Stocks & Commodities, March 1989"),

    P("negative-volume-index", "Negative Volume Index", "Fosback's Negative Volume Index above its one-year average", "volume",
      ["norman-fosback", "paul-dysart"], "D", FV.nvi,
      "A price index that moves only on days when volume shrinks, on the theory that quiet days show what informed investors are doing. Hold the stock while that index is above its one-year average.",
      ["The index starts at 1,000. On a day when volume is lower than the day before, it moves by that day's percentage price change. On other days it stays put.",
       "In when the index closes above its 255-day exponential average (Fosback's one-year average).",
       "Out when it closes below that average."],
      ["Fosback studied the index for the whole market. Running it on one stock's own price and volume follows modern charting practice (StockCharts, Fidelity).",
       "The one-year average is a 255-day exponential average, as on StockCharts. The type of average in Fosback's original test was not found.",
       "Daily changes compound, as in Fosback's formula.",
       "The rule needs about a year of history before its first call."],
      "Paul Dysart (1936); Norman Fosback, Stock Market Logic (1976)",
      sources=[("StockCharts ChartSchool: Negative Volume Index (NVI)", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/negative-volume-index-nvi"),
               ("Fidelity Learning Center: Negative Volume Index", "https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/nvi"),
               ("Wikipedia: Negative volume index", "https://en.wikipedia.org/wiki/Negative_volume_index")],
      warm=1500),
    P("force-index", "Force Index", "Elder's 13-day Force Index zero-line switch", "volume", ["alexander-elder"], "D", FV.force_index,
      "Each day's price change times its volume, smoothed over 13 days. Elder takes a value above zero to mean the bulls control the trend.",
      ["The 1-day Force Index is today's close minus yesterday's close, times today's volume.",
       "In when its 13-day exponential average is above zero.",
       "Out when it is below zero."],
      ["Elder uses the 13-day Force Index to read the intermediate trend and a 2-day version to time entries inside his Triple Screen. Using the 13-day zero line on its own is Be The Puck's simplification.",
       "There is no buffer around zero, so the call can flip often when the line hugs zero."],
      "Trading for a Living (1993)",
      sources=[("StockCharts ChartSchool: Force Index", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/force-index"),
               ("Incredible Charts: Force Index", "https://incrediblecharts.com/indicators/force_index.php"),
               ("Traders.com (Working Money, 2005): Paolo Pezzutti on the Force Index", "https://technical.traders.com/tradersonline/display.asp?art=2648")]),
    P("buff-averages", "Buff Averages", "Dormeier's 5/20-day volume-weighted moving average crossover", "volume", ["buff-dormeier"], "D", FV.buff,
      "Two moving averages that give heavy-volume days more weight, 5 and 20 days long. Hold while the fast one is above the slow one.",
      ["A volume-weighted average adds up each day's close times its volume and divides by the total volume, so busy days count more.",
       "In when the 5-day volume-weighted average is above the 20-day one.",
       "Out when it is below."],
      ["Dormeier's 2001 test also went short on the down-cross. Be The Puck holds T-bills instead.",
       "Signals are taken on the close of the crossover day."],
      "Technical Analysis of Stocks & Commodities, February 2001 ('Buff Up Your Moving Averages')",
      sources=[("Traders.com: Dormeier, 'Buff Up Your Moving Averages' (S&C, February 2001)", "https://traders.com/Documentation/FEEDbk_docs/2001/02/Abstracts_new/Dormeier/Dormeier.html")]),
    P("chaikin-oscillator", "Chaikin Oscillator", "Chaikin Oscillator zero-line switch (3- and 10-day EMAs of the A/D line)", "volume", ["marc-chaikin"], "D", FV.chaikin_osc,
      "Measures the momentum of Chaikin's Accumulation/Distribution line. Hold while it is above zero, when buying pressure has the upper hand.",
      ["The Accumulation/Distribution line is a running total of volume, weighted by where each close sits in the day's range: fully added at the high, fully subtracted at the low.",
       "The oscillator is the line's 3-day exponential average minus its 10-day one.",
       "In when the oscillator is above zero.",
       "Out when it is below zero."],
      ["StockCharts also reads divergences. This rule uses only the zero line.",
       "A day with no range (high equals low) adds no volume to the line."],
      "Marc Chaikin (date unverified)",
      sources=[("StockCharts ChartSchool: Chaikin Oscillator", "https://chartschool.stockcharts.com/table-of-contents/technical-indicators-and-overlays/technical-indicators/chaikin-oscillator"),
               ("Wikipedia: Accumulation/distribution index (Chaikin oscillator)", "https://en.wikipedia.org/wiki/Accumulation/distribution_index")]),
    P("volume-flow-indicator", "Volume Flow Indicator", "Katsanos' Volume Flow Indicator (VFI) zero-line switch", "volume", ["markos-katsanos"], "D", FV.vfi,
      "A refined on-balance volume that ignores tiny price moves and caps freak volume spikes. Hold while it is above zero.",
      ["Each day's volume counts as buying if the typical price (the average of high, low and close) rose by more than a small cutoff, as selling if it fell by more than the cutoff, and as nothing otherwise. The cutoff is 0.2 times the stock's recent daily volatility.",
       "Volume is capped at 2.5 times its 130-day average. The VFI is the 130-day sum of the signed volume divided by average volume, smoothed over 3 days.",
       "In when the VFI is above zero.",
       "Out when it is below zero."],
      ["Settings are Katsanos' published daily defaults: 130 days, cutoff 0.2, volume cap 2.5, smoothing 3. The 30-day volatility window comes from the standard published code.",
       "Average volume is the 130-day average up to the day before, as in the published code.",
       "Katsanos also stresses divergences, which are not used."],
      "Technical Analysis of Stocks & Commodities, June 2004 ('Using Money Flow To Stay With The Trend')",
      sources=[("Traders.com: Traders' Tips, June 2004 (VFI code and parameters)", "https://traders.com/Documentation/FEEDbk_docs/2004/06/TradersTips/TradersTips.html"),
               ("ProRealCode: Volume Flow Indicator (Katsanos, 2004) code and signal description", "https://prorealcode.com/prorealtime-indicators/volume-flow-indicator"),
               ("TradingView: VFI script (daily vs intraday defaults)", "https://www.tradingview.com/script/kPeyW7i5/")]),
    P("klinger-oscillator", "Klinger Oscillator", "Klinger Volume Oscillator (34/55-day, 13-day trigger)", "volume", ["stephen-klinger"], "D", FV.klinger,
      "Volume signed by the direction of the day's typical price and weighted by how long that direction has lasted, run through 34 and 55-day averages. Hold while it is above its 13-day trigger line.",
      ["Volume force is each day's volume, counted as plus when high + low + close rises and minus when it falls, and weighted more heavily the longer the current run of same-direction days has lasted.",
       "The oscillator is the 34-day exponential average of volume force minus the 55-day one. The trigger is its 13-day exponential average.",
       "In when the oscillator is above the trigger.",
       "Out when it is below."],
      ["Klinger put most weight on extreme readings that reverse and on divergences. The trigger-line cross is the standard published signal (CQG and others).",
       "Some versions drop the absolute value in the volume-force formula, which flips its sign. The absolute-value form is used here.",
       "The range count starts on the first day of history, and days with no range at all get no volume force."],
      "Technical Analysis of Stocks & Commodities, December 1997 ('Identifying Trends With Volume Analysis')",
      sources=[("CQG News: Klinger Volume Oscillator (periods and crossover rule)", "https://news.cqg.com/node/1508"),
               ("One Trade Journal: Klinger oscillator and volume force formula", "https://onetradejournal.com/indicators/klinger-oscillator"),
               ("Traders.com: Klinger article excerpt (December 1997)", "https://traders.com/Documentation/FEEDbk_docs/1997/12/Abstracts_new/Klinger9712/Kinger.html")]),

    # ------------------------------------------------------------ candles & chart patterns
    P("engulfing-switch", "Engulfing Switch", "Nison bullish/bearish engulfing reversal switch", "pattern", ["steve-nison", "thomas-bulkowski"], "D", FV.engulfing,
      "Buy after a bullish engulfing candle ends a decline; sell after a bearish engulfing candle ends a rally. An engulfing candle's body swallows the whole body of the day before.",
      ["Bullish engulfing: after a decline, a down day (close below open) is followed by an up day that opens at or below the prior close and closes at or above the prior open.",
       "Bearish engulfing: after a rise, an up day is followed by a down day that opens at or above the prior close and closes at or below the prior open.",
       "In at the close of a bullish engulfing day. Out at the close of a bearish engulfing day. Otherwise the rule keeps its last call."],
      ["A decline (or rise) means the prior close is below (or above) the close 5 sessions before it. Nison and Bulkowski require a prior trend but give no number.",
       "Nison weighs support, resistance and confirmation, which a mechanical rule cannot judge. No confirmation day is required here.",
       "Shadows are ignored, as both Nison and Bulkowski allow. One edge of the new body may equal the old body's edge, as in the TA-Lib pattern library, but not both.",
       "Crypto trades around the clock, so a coin's daily open is just the prior close. For coins the open is taken as the prior close, and the pattern becomes a close beyond the prior day's open."],
      "Japanese Candlestick Charting Techniques (1991); statistics in Encyclopedia of Candlestick Charts (2008)",
      sources=[("ThePatternSite: Bullish Engulfing (identification and statistics)", "https://www.thepatternsite.com/BullEngulfing.html"),
               ("ThePatternSite: Bearish Engulfing (identification and statistics)", "https://thepatternsite.com/BearEngulfing.html"),
               ("StockCharts ChartSchool: Candlestick bullish reversal patterns", "https://chartschool.stockcharts.com/table-of-contents/chart-analysis/candlestick-charts/candlestick-bullish-reversal-patterns")]),
    P("hikkake", "Hikkake", "Chesler's hikkake (inside-day false breakout) switch", "pattern", ["daniel-chesler"], "D", FV.hikkake,
      "When a stock breaks down out of an inside day and then reverses back above the inside day's high within 3 days, buy the reversal that traps the sellers.",
      ["Setup: an inside day (a lower high and a higher low than the day before), then a day with a lower high and a lower low than the inside day (bullish) or a higher high and a higher low (bearish).",
       "In at the close if, within 3 sessions after a bullish setup, a close is above the inside day's high. The stop is the lowest low of the pattern.",
       "Out at the close if a close falls below that stop, or if a bearish setup is confirmed by a close below the inside day's low within 3 sessions."],
      ["Chesler enters during the day when price crosses the inside day's high. On daily bars the close must clear it.",
       "Chesler gives no profit target, so a trade ends only at the stop or on an opposite hikkake.",
       "If a newer setup forms, it replaces the older one."],
      "Daniel Chesler, 'Trading False Moves with the Hikkake Pattern', Active Trader (April 2004)",
      sources=[("Chesler, 'Trading False Moves with the Hikkake Pattern', Active Trader (April 2004), PDF", "https://c.mql5.com/forextsd/forum/34/hikkake.pdf"),
               ("Wikipedia: Hikkake pattern", "https://en.wikipedia.org/wiki/Hikkake_pattern")]),
    P("turtle-soup-plus-one", "Turtle Soup Plus One", "Raschke & Connors' Turtle Soup Plus One (failed 20-day breakdown)", "pattern",
      ["linda-bradford-raschke", "larry-connors"], "D", FV.turtle_soup,
      "Buy when a stock closes at a new 20-day low and climbs back above the old low the next day, betting the breakdown was a trap. It turns the Turtles' breakout rule on its head.",
      ["Day 1: the close is below the lowest low of the prior 20 sessions, and that low was set at least 3 sessions earlier.",
       "Day 2: in at the close if the close is back above that old 20-day low.",
       "Out at the close if a close falls below the lower of the day-1 and day-2 lows (the stop), or after 6 sessions in the trade."],
      ["The book buys during day 2 with a stop order at the old low. On daily bars the close must be above it.",
       "The book takes partial profits within 2 to 6 bars and trails a stop on the rest. A 6-session time exit stands in for both.",
       "The original Turtle Soup (same-day entry, old low at least 4 days back) is the sister pattern. Plus One is used because it waits for a closing confirmation.",
       "The authors also sell short failed breakouts to new highs. Be The Puck tests only the long side."],
      "Street Smarts: High Probability Short-Term Trading Strategies (1995)",
      sources=[("QuantNet forum: Turtle Soup Plus One rules quoted from Street Smarts", "https://quantnet.com/threads/need-vba-help-for-trading-tool.2769/latest"),
               ("MQL5: 'Turtle Soup' and 'Turtle Soup Plus One' formalised from Street Smarts", "https://www.mql5.com/tr/articles/2717"),
               ("Traders.com (Working Money, 2005): Pezzutti, 'Short-Term Patterns: Turtle Soup'", "https://technical.traders.com/tradersonline/display.asp?art=2414")]),

    # ------------------------------------------------------------ calendar
    P("halloween-indicator", "Halloween Indicator", "Halloween indicator (sell in May)", "calendar", ["bouman-jacobsen", "yale-jeffrey-hirsch"], "D", F.halloween,
      "Own stocks from November through April; sit in T-bills from May through October.",
      ["In at the close on the last trading day of October.", "Out at the close on the last trading day of April."],
      ["The research used market indexes. Applying it to one stock assumes the season carries over."], "American Economic Review (2002); Stock Trader's Almanac (1986)",
      calendar=True),
    P("best-six-months-macd", "Best Six + MACD", "Almanac Best Six Months with MACD timing", "calendar", ["yale-jeffrey-hirsch"], "D", F.best_six_macd,
      "The Almanac's refinement of the Best Six Months: wait for a MACD buy signal from October 1, and a MACD sell signal from April 1.",
      ["In on the first MACD (8, 17, 9) cross above its signal line on or after October 1.", "Out on the first cross below on or after April 1."],
      ["The Almanac requires the Dow, S&P 500 and Nasdaq to agree. Be The Puck applies the MACD to the stock itself.",
       "The sell-side MACD settings are not published; 8, 17, 9 is assumed."], "Stock Trader's Almanac",
      season=((10, 1), (4, 1))),
    P("seasonal-timing-strategy", "Seasonal Timing", "Sy Harding's Seasonal Timing Strategy", "calendar", ["sy-harding"], "D", F.harding,
      "Enter around October 16 and exit around April 20, but let MACD shift each date: wait for a buy signal if it isn't on one, and hold for a sell signal if it isn't.",
      ["From October 16, in on the first day MACD is above its signal line.", "From April 20, out on the first day MACD is below it."],
      ["Harding applied it to the Dow. His MACD settings were never published; 12, 26, 9 is assumed."], "Street Smart Report (1999)",
      season=((10, 16), (4, 20))),
    P("santa-claus-rally", "Santa Claus Rally", "Santa Claus rally", "calendar", ["yale-jeffrey-hirsch"], "D", F.santa,
      "The last five trading days of December and the first two of January. That's it: seven days a year.",
      ["In at the close six trading days before year-end.", "Out at the close on the second trading day of January."],
      ["Hirsch described a market tendency, not a stand-alone system for single stocks."], "Stock Trader's Almanac (defined 1972)", calendar=True),
    P("turn-of-the-month", "Turn of the Month", "Turn-of-the-month effect", "calendar", ["lakonishok-smidt", "robert-ariel"], "D", F.turn_of_month,
      "Returns bunch up around the start of each month. Hold for four trading days: the last day of a month and the first three of the next.",
      ["In at the close two trading days before month-end.", "Out at the close on the third trading day of the new month."],
      ["The studies measured index returns, not single stocks, and were descriptive rather than trading systems."],
      "Journal of Financial Economics (1987); Review of Financial Studies (1988)", calendar=True),

    P("presidential-sweet-spot", "Presidential Sweet Spot", "Presidential-cycle sweet spot (Q4 of the midterm year to Q2 of the pre-election year)", "calendar",
      ["yale-jeffrey-hirsch"], "D", FV.presidential,
      "Own stocks only in the strongest stretch of the 4-year presidential cycle: from the start of the fourth quarter of a midterm-election year to the end of June of the year after.",
      ["In at the close on the last trading day of September in a U.S. midterm-election year (2018, 2022, 2026 ...).",
       "Out at the close on the last trading day of June in the pre-election year that follows.",
       "Out for the other 13 quarters of every 4-year cycle."],
      ["The Almanac measures the sweet spot on the Dow, S&P 500 and Nasdaq. Applying it to a single stock is Be The Puck's extension.",
       "The Hirsches present the cycle as a seasonal tendency, not a mechanical system. Sitting out the rest of the time is Be The Puck's switch.",
       "Quarter boundaries are taken at the last close of September and of June."],
      "Stock Trader's Almanac (Yale Hirsch, first edition 1967); 'sweet spot' framing by Jeffrey Hirsch, e.g. Almanac alert of 13 September 2018",
      sources=[("Stock Trader's Almanac: 'Q3 Update: Sweet Spot Still Looks Good' (2018)", "https://stocktradersalmanac.com/Alert/20180913.aspx"),
               ("Ritholtz Wealth, At The Money: Jeff Hirsch on Presidential Investing Cycles (2025)", "https://ritholtz.com/2025/01/atm-presidential-investing-cycles"),
               ("MoneyShow: Almanac presidential-cycle year-by-year averages", "https://moneyshow.com/articles/no-nonsense-30687")],
      calendar=True),
    P("pre-holiday", "Pre-Holiday", "Pre-holiday effect (the trading day before NYSE holidays)", "calendar", ["robert-ariel", "lakonishok-smidt"], "D", FV.pre_holiday,
      "Own the stock only on the last trading day before each stock-market holiday, a day that has historically paid many times the average daily return.",
      ["In at the close 2 sessions before a regular NYSE holiday, so the stock is held for the last session before the holiday.",
       "Out at the close of that last session.",
       "Out on every other day."],
      ["Holidays are the regular NYSE closures: New Year's Day, Martin Luther King Jr. Day (from 1998), Presidents' Day, Good Friday, Memorial Day, Juneteenth (from 2022), Independence Day, Labor Day, Thanksgiving and Christmas. Ariel's 1963-82 sample had 8 holidays a year.",
       "Unscheduled closures, such as after 9/11, Hurricane Sandy or national days of mourning, are ignored.",
       "Canadian stocks are held on the same U.S. pre-holiday dates. Canadian-only holidays are not used.",
       "Crypto trades every day, so it has no pre-holiday session of its own. Coins are held on the same dates as stocks: the last U.S. trading day before each NYSE holiday."],
      "Lakonishok & Smidt, Review of Financial Studies (1988); Ariel, Journal of Finance (1990)",
      sources=[("IDEAS/RePEc: Ariel (1990), 'High Stock Returns before Holidays: Existence and Evidence on Possible Causes', Journal of Finance", "https://ideas.repec.org/a/bla/jfinan/v45y1990i5p1611-26.html"),
               ("Lakonishok & Smidt (1988), 'Are Seasonal Anomalies Real? A Ninety-Year Perspective' (abstract)", "https://academicnewsletter.sufe.edu.cn/info/355994")],
      calendar=True),
    P("january-barometer", "January Barometer", "Hirsch's January Barometer: as the S&P 500 goes in January, so goes the year", "calendar",
      ["yale-jeffrey-hirsch"], "M", FV.jan_barometer,
      "If the S&P 500 rises in January, hold the stock for the rest of the year. If it falls, sit out until next January.",
      ["At the last close of January, measure SPY's January return: its last January close against its last December close.",
       "In from that close to the last close of December if the return is above zero.",
       "Out from that close to the last close of December if it is zero or below.",
       "In during January itself, while the new reading forms."],
      ["Hirsch uses the S&P 500 index. SPY's price stands in for it.",
       "The barometer forecasts the year but says nothing about January itself. Holding through January is Be The Puck's choice.",
       "The signal uses the market's January, as Hirsch did, not the stock's own. On SPY the two are the same.",
       "The call can change only at 2 month-ends a year: the last close of January and of December."],
      "Devised by Yale Hirsch in 1972; Stock Trader's Almanac",
      sources=[("Stock Trader's Almanac: 'The Incredible January Barometer' (2015)", "https://stocktradersalmanac.com/Alert/20150120.aspx"),
               ("Barry Popik: 'As January goes, so goes the year' (origin and Almanac quotes)", "https://barrypopik.com/blog/as_january_goes_so_goes_the_year_wall_street_proverb")]),
    P("weekend-effect", "Weekend Effect", "Weekend (Monday) effect: skip the Friday-to-Monday return", "calendar", ["kenneth-french", "lakonishok-smidt"], "D", FV.weekend,
      "Step out at the week's last close and buy back at the next week's first close, skipping the weekend-plus-Monday stretch that used to lose money.",
      ["Out at the close of the last session of each week, normally Friday.",
       "In at the close of the first session of the next week, normally Monday.",
       "So the stock is held from Monday's close to Friday's close and skips the weekend and Monday."],
      ["When Monday is a holiday, the week's first session (Tuesday) plays Monday's role. A week with a single session stays out.",
       "Robins and Smith find the effect vanished after 1975, before it was even published. The rule is kept to show what a famous anomaly does after discovery.",
       "Crypto trades on weekends too. Coins skip the same stretch as stocks, from Friday's close to Monday's close.",
       "About 100 switches a year means trading costs matter a lot here."],
      "Kenneth French, Journal of Financial Economics (1980); Lakonishok & Smidt, Review of Financial Studies (1988)",
      sources=[("International Journal of Financial Studies (MDPI): citation of French (1980), J. Financ. Econ. 8: 55-69", "https://www.mdpi.com/2227-7072/4/2/7"),
               ("ASU W. P. Carey: Robins & Smith on the weekend effect", "https://news.wpcarey.asu.edu/20171204-research-debunks-myth-stock-market-weekend-effect"),
               ("Lakonishok & Smidt (1988) abstract: turn-of-the-week anomalies", "https://academicnewsletter.sufe.edu.cn/info/355994")],
      calendar=True),
    P("pre-fomc-drift", "Pre-FOMC Drift", "Pre-FOMC announcement drift (Lucca & Moench)", "calendar", ["lucca-moench"], "D", FV.pre_fomc,
      "Own the stock only on the day of each scheduled Federal Reserve rate announcement, when stocks have tended to rise ahead of the news.",
      ["In at the close of the session before each scheduled FOMC announcement day (the last day of a scheduled meeting).",
       "Out at the close of the announcement day.",
       "Out on all other days. Conference calls, unscheduled meetings and notation votes are ignored."],
      ["The paper measures 2 p.m. to 2 p.m. Daily closes capture 4 p.m. to 4 p.m. instead, which includes about 2 hours after the statement.",
       "Dates are the 271 scheduled meetings from 1994 to 2027 on federalreserve.gov. Before 1994 the Fed made no same-day announcements, so the rule is out. Dates after 2027 are added as the Fed publishes them.",
       "Kurov, Wolfe and Gilbert (2021) find the drift essentially disappeared after 2015. The rule is kept to show that.",
       "Crypto is held over the same calendar day, which also contains the 2 p.m. statement."],
      "Lucca & Moench, Journal of Finance (2015); NY Fed Staff Report 512 (2011)",
      sources=[("Liberty Street Economics: the 24-hour pre-FOMC window", "https://libertystreeteconomics.newyorkfed.org/?p=1112"),
               ("Federal Reserve: FOMC meeting calendars 2021-2027", "https://federalreserve.gov/monetarypolicy/fomccalendars.htm"),
               ("Federal Reserve: FOMC transcripts and historical materials (meeting lists by year)", "https://federalreserve.gov/monetarypolicy/fomc_historical.htm"),
               ("IDEAS/RePEc: Kurov, Wolfe & Gilbert (2021), 'The disappearing pre-FOMC announcement drift'", "https://ideas.repec.org/a/eee/finlet/v40y2021ics1544612320315956.html")],
      calendar=True),
    P("lunar-cycle", "Lunar Cycle", "New-moon versus full-moon lunar cycle effect", "calendar", ["yuan-zheng-zhu"], "D", FV.lunar,
      "Own the stock around the new moon and step aside for the 15 days centred on each full moon.",
      ["The full-moon period is the day of the full moon plus the 7 calendar days before and after it, using U.S. Naval Observatory dates.",
       "Out for any session that falls in a full-moon period.",
       "In for the rest of the lunar month (the new-moon period)."],
      ["The paper went long in new-moon periods and short in full-moon periods. Be The Puck holds T-bills instead of shorting.",
       "Session dates are compared with the full-moon date in universal time (GMT) with no time-zone shift, as in the paper.",
       "Dichev and Janes (2003) found a similar new-moon advantage in U.S. indexes back to 1896. The 15-day definition here follows Yuan, Zheng and Zhu.",
       "Moon dates on file run from 1990 to 2030; earlier history gets no call."],
      "Yuan, Zheng & Zhu, Journal of Empirical Finance (2006); earlier Dichev & Janes (2003)",
      sources=[("University of Michigan working paper: window definitions and USNO dates", "https://www.bus.umich.edu/pdf/mitsui/workshopdocs/ZhengMoonstruck.pdf"),
               ("LSE-hosted paper PDF: 15-day and 7-day windows, long new moon / short full moon", "https://personal.lse.ac.uk/yuan/papers/lunar.pdf"),
               ("Hull Tactical: summary of Dichev & Janes' lunar results", "https://hulltactical.com/?p=1494"),
               ("U.S. Naval Observatory moon-phase API (source of the date list)", "https://aa.usno.navy.mil/api/moon/phases/year?year=2024")],
      calendar=True),

    # ------------------------------------------------------------ benchmark
    P("buy-and-hold", "Buy & Hold", "Buy and hold (benchmark)", "benchmark", ["john-bogle"], "D", F.hold,
      "Own it and never sell. Every other play on Be The Puck is graded against this one.", ["Always in."], [], "", benchmark=True),
]

# Every play is core: each one runs on every covered stock and gets its own page there.
# The 20 below are the ones a newcomer should learn first (the "20 plays to learn first"
# article): the most widely taught and followed rule from each corner of technical trading.
STARTER_SLUGS = [
    "200-day-rule", "golden-cross", "ten-month-sma", "stage-analysis", "trend-template", "ichimoku-cloud",
    "parabolic-sar", "macd-signal-cross", "four-week-rule", "turtle-system-2", "bollinger-breakout",
    "time-series-momentum", "dual-momentum", "52-week-high", "rsi-30-70", "rsi-2-pullback", "stochastic-20-80",
    "on-balance-volume", "halloween-indicator", "supertrend",
]
for _p in PLAYS:
    _p["core"] = not _p.get("benchmark")
    _p["starter"] = _p["slug"] in STARTER_SLUGS

PLAY = {p["slug"]: p for p in PLAYS}
TIMED = [p for p in PLAYS if not p.get("benchmark")]
STARTER = [next(p for p in TIMED if p["slug"] == s) for s in STARTER_SLUGS]
assert len(STARTER) == 20
BAR_WORD = {"D": "daily", "W": "weekly", "M": "month-end"}


def by_family():
    return [(k, FAMILY[k][0], [p for p in TIMED if p["family"] == k]) for k in FAMILY_ORDER]
